TRANSFER-TYPE 2;
WINDOW 202350,706750,208500,709500;
SURVEYOR 593;
GUSH 8705;
SCALE 2500;
SURVEY-DATE 24/09/2012;
WORK-ORDER 99999999;
SETTLEMENT 6500;
MUNICIPALITY 6500;
COUNTY 32;
SHEET-NUM 1;
TALAR-NUM 1324/2013;
TALAR-SERIAL ג.ב./2012/634/5;
FINISH-DATE 25/10/2012;
PARCELS 1-8,10,11,13-17,28-30,31;
PLACE חריש;
ORDERER משרד הבינוי והשיכון-חיפה;
TALAR-COMMENT הגבולות ושטח החלקה(ות) 1-8,10,11,13-16,28-30,31 נלקחו ממפת גוש רישום מס. 8705.
כל הגבולות שלא תוארו אחרת הם לא מסויגים.
כל סימני המדידה שלא תוארו אחרת הם מסוג לא סומנו בשדה.
הגבולות נמדדו בשיטה אנליטית והפרטים בשיטה פוטוגרמטרית.
התוכנית הוכנה בהתאם לתבע מספר חריש/1/א.;
TABA-NAMES חריש/1/א;
AREA-UNITS DUNAM;
