'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
   <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
    Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
    Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
    Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
   Friend Module Resources1

      Private resourceMan As Global.System.Resources.ResourceManager

      Private resourceCulture As Global.System.Globalization.CultureInfo

      '''<summary>
      '''  Returns the cached ResourceManager instance used by this class.
      '''</summary>
      <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
      Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
         Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
               Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TopoUI.Resources", GetType(Resources).Assembly)
               resourceMan = temp
            End If
            Return resourceMan
         End Get
      End Property

      '''<summary>
      '''  Overrides the current thread's CurrentUICulture property for all
      '''  resource lookups using this strongly typed resource class.
      '''</summary>
      <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
      Friend Property Culture() As Global.System.Globalization.CultureInfo
         Get
            Return resourceCulture
         End Get
         Set(value As Global.System.Globalization.CultureInfo)
            resourceCulture = Value
         End Set
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property _1447_eraser() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("1447_eraser", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property _27() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("27", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property _65() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("65", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property _Erase() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Erase", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property _Exit() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Exit", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property _New() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("New", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property _Select() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Select", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Acrobat16() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Acrobat16", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ArrowLeft16Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ArrowLeft16Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property AStyle() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("AStyle", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Block1620() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Block1620", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property book_notebook() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("book_notebook", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property book_notebook20() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("book_notebook20", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property book_notebook24() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("book_notebook24", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property book_notebook28() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("book_notebook28", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Brush() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Brush", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property BrushTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("BrushTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Cancel16() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Cancel16", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Check16Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Check16Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Checkbox32Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Checkbox32Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property CheckP32Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("CheckP32Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Cleanup() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Cleanup", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Clear32Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Clear32Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property CloseForm() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("CloseForm", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ColorHS() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ColorHS", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ColorHS1() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ColorHS1", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ColorPgonsTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ColorPgonsTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property CreateTopo() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("CreateTopo", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property DataContainer_MoveNextHS_80() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("DataContainer_MoveNextHS_80", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property DataContainer_MoveNextHS_801() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("DataContainer_MoveNextHS_801", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property DataContainer_MoveNextHS_90() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("DataContainer_MoveNextHS_90", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property DataContainer_MoveNextHS_901() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("DataContainer_MoveNextHS_901", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Delete() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Delete1() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Delete1", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property DoneTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("DoneTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property DownTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("DownTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property DWG16Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("DWG16Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Edit_UndoHL() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Edit_UndoHL", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Edit32Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Edit32Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property EditInformationHS() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("EditInformationHS", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Erase1() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Erase1", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Eraser15Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Eraser15Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Event10() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Event10", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Excel() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Excel", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Exit24Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Exit24Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Exit32Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Exit32Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Export16() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Export16", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property FilterBySelect() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("FilterBySelect", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Find15x15Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Find15x15Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Finish25Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Finish25Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Form15() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Form15", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Frame32() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Frame32", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property GushTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("GushTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ImpExcel15Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ImpExcel15Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Import16Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Import16Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Invert12() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Invert12", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property LayerOff() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("LayerOff", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property LayerOn() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("LayerOn", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Layers16() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Layers16", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Layers16Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Layers16Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Left25Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Left25Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property LeftTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("LeftTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property MoveFirstTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("MoveFirstTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property MoveLastTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("MoveLastTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property MoveNextTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("MoveNextTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property MovePrevTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("MovePrevTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property OK_B() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("OK_B", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property OK16() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("OK16", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property openfolderHS() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("openfolderHS", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Paint20Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Paint20Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Plus16Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Plus16Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Plus32Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Plus32Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Plus34Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Plus34Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property PrintPreviewHL() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("PrintPreviewHL", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property PrintPreviewHL1() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("PrintPreviewHL1", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Properties() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Properties", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Properties1() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Properties1", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property QuestionMark() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("QuestionMark", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Rect16() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Rect16", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Refresh22Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Refresh22Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Refresh22Tr1() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Refresh22Tr1", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Refresh32Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Refresh32Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property RefreshA() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("RefreshA", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property RefreshC() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("RefreshC", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property RemoveFilter() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("RemoveFilter", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Right25Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Right25Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Right32Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Right32Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property RightTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("RightTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Run15Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Run15Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Save() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Save_20() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Save_20", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Save32Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Save32Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property SaveAllHS() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("SaveAllHS", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property SaveDWG32Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("SaveDWG32Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property SaveFormDesignHS() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("SaveFormDesignHS", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property saveHS() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property SavePencil() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("SavePencil", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ShowTopo() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ShowTopo", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Start20Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Start20Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Start25Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Start25Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized string similar to בדיקת טופולוגיה.
      '''</summary>
      Friend ReadOnly Property StrCheckTopo() As String
         Get
            Return ResourceManager.GetString("StrCheckTopo", resourceCulture)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized string similar to יצירת טופולוגיה.
      '''</summary>
      Friend ReadOnly Property StrCreateTopo() As String
         Get
            Return ResourceManager.GetString("StrCreateTopo", resourceCulture)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized string similar to מחיקת טופולוגיה.
      '''</summary>
      Friend ReadOnly Property StrDeleteTopo() As String
         Get
            Return ResourceManager.GetString("StrDeleteTopo", resourceCulture)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized string similar to הצגת גיאומטריה.
      '''</summary>
      Friend ReadOnly Property StrShowTopoGeometry() As String
         Get
            Return ResourceManager.GetString("StrShowTopoGeometry", resourceCulture)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized string similar to שכבות.
      '''</summary>
      Friend ReadOnly Property StrTopoLayers() As String
         Get
            Return ResourceManager.GetString("StrTopoLayers", resourceCulture)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized string similar to סטטיסטיקה.
      '''</summary>
      Friend ReadOnly Property StrTopoStatistics() As String
         Get
            Return ResourceManager.GetString("StrTopoStatistics", resourceCulture)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Table19x17() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Table19x17", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ToClosedPgons() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ToClosedPgons", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property UncheckP32Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("UncheckP32Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Undo() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Undo", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Unidiv() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Unidiv", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property UpTr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("UpTr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Util16Tr() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Util16Tr", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Util16Tr1() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Util16Tr1", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Validate() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Validate", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property Validate1() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("Validate1", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property View() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("View", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property World14() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("World14", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property
   End Module
End Namespace
