Option Explicit On
Option Strict On
Imports TopoManager
Public Class AcadErrCode
   Public Shared Function GetAcadErrText(ByVal iErrCode As Integer) As String
      Select Case iErrCode

         '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
         Case 331 : Return "eNotFromThisDocument"
         Case 332 : Return "eLISPActive"
         Case 333 : Return "eTargetDocNotQuiescent"
         Case 334 : Return "eDocumentSwitchDisabled"
         Case 335 : Return "eInvalidContext"
         Case 337 : Return "eCreateFailed"
         Case 338 : Return "eCreateInvalidName"
         Case 340 : Return "eSetFailed"
         Case 342 : Return "eDelDoesNotExist"
         Case 343 : Return "eDelIsModelSpace"
         Case 344 : Return "eDelLastLayout"
         Case 345 : Return "eDelUnableToSetCurrent"
         Case 346 : Return "eDelUnableToFind"
         Case 348 : Return "eRenameDoesNotExist"
         Case 349 : Return "eRenameIsModelSpace"
         Case 350 : Return "eRenameInvalidLayoutName"
         Case 351 : Return "eRenameLayoutAlreadyExists"
         Case 352 : Return "eRenameInvalidName"
         Case 354 : Return "eCopyDoesNotExist"
         Case 355 : Return "eCopyIsModelSpace"
         Case 356 : Return "eCopyFailed"
         Case 357 : Return "eCopyInvalidName"
         Case 358 : Return "eCopyNameExists"
         Case 359 : Return "eProfileDoesNotExist"
         Case 360 : Return "eInvalidFileExtension"
         Case 361 : Return "eInvalidProfileName"
         Case 362 : Return "eFileExists"
         Case 363 : Return "eProfileIsInUse"
         Case 364 : Return "eCantOpenFile"
         Case 365 : Return "eNoFileName"
         Case 366 : Return "eRegistryAccessError"
         Case 367 : Return "eRegistryCreateError"
         Case 368 : Return "eBadDxfFile"
         Case 369 : Return "eUnknownDxfFileFormat"
         Case 370 : Return "eMissingDxfSection"
         Case 371 : Return "eInvalidDxfSectionName"
         Case 372 : Return "eNotDxfHeaderGroupCode"
         Case 373 : Return "eUndefinedDxfGroupCode"
         Case 374 : Return "eNotInitializedYet"
         Case 375 : Return "eInvalidDxf2dPoint"
         Case 376 : Return "eInvalidDxf3dPoint"
         Case 378 : Return "eBadlyNestedAppData"
         Case 379 : Return "eIncompleteBlockDefinition"
         Case 380 : Return "eIncompleteComplexObject"
         Case 381 : Return "eBlockDefInEntitySection"
         Case 382 : Return "eNoBlockBegin"
         Case 383 : Return "eDuplicateLayerName"
         Case 384 : Return "eBadPlotStyleName"
         Case 385 : Return "eDuplicateBlockName"
         Case 386 : Return "eBadPlotStyleType"
         Case 387 : Return "eBadPlotStyleNameHandle"
         Case 388 : Return "eUndefineShapeName"
         Case 389 : Return "eDuplicateBlockDefinition"
         Case 390 : Return "eMissingBlockName"
         Case 391 : Return "eBinaryDataSizeExceeded"
         Case 392 : Return "eObjectIsReferenced"
         Case 393 : Return "eNoThumbnailBitmap"
         Case 394 : Return "eGuidNoAddress"
         Case 395 : Return "eMustBe0to2"
         Case 396 : Return "eMustBe0to3"
         Case 397 : Return "eMustBe0to4"
         Case 398 : Return "eMustBe0to5"
         Case 399 : Return "eMustBe0to8"
         Case 400 : Return "eMustBe1to8"
         Case 401 : Return "eMustBe1to15"
         Case 402 : Return "eMustBePositive"
         Case 403 : Return "eMustBeNonNegative"
         Case 404 : Return "eMustBeNonZero"
         Case 405 : Return "eMustBe1to6"
         Case 406 : Return "eNoPlotStyleTranslationTable"
         Case 407 : Return "ePlotStyleInColorDependentMode"
         Case 408 : Return "eMaxLayouts"
         Case 409 : Return "eNoClassId"
         Case 410 : Return "eUndoOperationNotAvailable"
         Case 411 : Return "eUndoNoGroupBegin"
         Case 420 : Return "eHatchTooDense"
         Case 430 : Return "eOpenFileCancelled"
         Case 431 : Return "eNotHandled"
         Case 432 : Return "eMakeMeProxyAndResurrect"
         Case 0 : Return "eInetOk"
         Case 0 : Return "eInetInCache"
         Case 0 : Return "eInetFileNotFound"
         Case 0 : Return "eInetBadPath"
         Case 0 : Return "eInetTooManyOpenFiles"
         Case 0 : Return "eInetFileAccessDenied"
         Case 0 : Return "eInetInvalidFileHandle"
         Case 0 : Return "eInetDirectoryFull"
         Case 0 : Return "eInetHardwareError"
         Case 0 : Return "eInetSharingViolation"
         Case 0 : Return "eInetDiskFull"
         Case 0 : Return "eInetFileGenericError"
         Case 0 : Return "eInetValidURL"
         Case 0 : Return "eInetNotAnURL"
         Case 0 : Return "eInetNoWinInet"
         Case 0 : Return "eInetOldWinInet"
         Case 0 : Return "eInetNoAcadInet"
         Case 0 : Return "eInetNotImplemented"
         Case 0 : Return "eInetProtocolNotSupported"
         Case 0 : Return "eInetCreateInternetSessionFailed"
         Case 0 : Return "eInetInternetSessionConnectFailed"
         Case 0 : Return "eInetInternetSessionOpenFailed"
         Case 0 : Return "eInetInvalidAccessType"
         Case 0 : Return "eInetFileOpenFailed"
         Case 0 : Return "eInetHttpOpenRequestFailed"
         Case 0 : Return "eInetUserCancelledTransfer"
         Case 0 : Return "eInetHttpBadRequest"
         Case 0 : Return "eInetHttpAccessDenied"
         Case 0 : Return "eInetHttpPaymentRequired"
         Case 0 : Return "eInetHttpRequestForbidden"
         Case 0 : Return "eInetHttpObjectNotFound"
         Case 0 : Return "eInetHttpBadMethod"
         Case 0 : Return "eInetHttpNoAcceptableResponse"
         Case 0 : Return "eInetHttpProxyAuthorizationRequired"
         Case 0 : Return "eInetHttpTimedOut"
         Case 0 : Return "eInetHttpConflict"
         Case 0 : Return "eInetHttpResourceGone"
         Case 0 : Return "eInetHttpLengthRequired"
         Case 0 : Return "eInetHttpPreconditionFailure"
         Case 0 : Return "eInetHttpRequestTooLarge"
         Case 0 : Return "eInetHttpUriTooLong"
         Case 0 : Return "eInetHttpUnsupportedMedia"
         Case 0 : Return "eInetHttpServerError"
         Case 0 : Return "eInetHttpNotSupported"
         Case 0 : Return "eInetHttpBadGateway"
         Case 0 : Return "eInetHttpServiceUnavailable"
         Case 0 : Return "eInetHttpGatewayTimeout"
         Case 0 : Return "eInetHttpVersionNotSupported"
         Case 0 : Return "eInetInternetError"
         Case 0 : Return "eInetGenericException"
         Case 0 : Return "eInetUnknownError"
         Case 0 : Return "eAlreadyActive"
         Case 0 : Return "eAlreadyInactive"
         Case 0 : Return "eOk"
         Case 1 : Return "eNotImplementedYet"
         Case 2 : Return "eNotApplicable"
         Case 3 : Return "eInvalidInput"
         Case 4 : Return "eAmbiguousInput"
         Case 5 : Return "eAmbiguousOutput"
         Case 6 : Return "eOutOfMemory"
         Case 7 : Return "eBufferTooSmall"
         Case 8 : Return "eInvalidOpenState"
         Case 9 : Return "eEntityInInactiveLayout"
         Case 10 : Return "eHandleExists"
         Case 11 : Return "eNullHandle"
         Case 12 : Return "eBrokenHandle"
         Case 13 : Return "eUnknownHandle"
         Case 14 : Return "eHandleInUse"
         Case 15 : Return "eNullObjectPointer"
         Case 16 : Return "eNullObjectId"
         Case 17 : Return "eNullBlockName"
         Case 18 : Return "eContainerNotEmpty"
         Case 20 : Return "eNullEntityPointer"
         Case 21 : Return "eIllegalEntityType"
         Case 22 : Return "eKeyNotFound"
         Case 23 : Return "eDuplicateKey"
         Case 24 : Return "eInvalidIndex"
         Case 25 : Return "eDuplicateIndex"
         Case 26 : Return "eAlreadyInDb"
         Case 27 : Return "eOutOfDisk"
         Case 28 : Return "eDeletedEntry"
         Case 29 : Return "eNegativeValueNotAllowed"
         Case 30 : Return "eInvalidExtents"
         Case 31 : Return "eInvalidAdsName"
         Case 32 : Return "eInvalidSymbolTableName"
         Case 33 : Return "eInvalidKey"
         Case 34 : Return "eWrongObjectType"
         Case 35 : Return "eWrongDatabase"
         Case 36 : Return "eObjectToBeDeleted"
         Case 37 : Return "eInvalidDwgVersion"
         Case 38 : Return "eAnonymousEntry"
         Case 39 : Return "eIllegalReplacement"
         Case 40 : Return "eEndOfObject"
         Case 41 : Return "eEndOfFile"
         Case 42 : Return "eIsReading"
         Case 43 : Return "eIsWriting"
         Case 44 : Return "eNotOpenForRead"
         Case 45 : Return "eNotOpenForWrite"
         Case 46 : Return "eNotThatKindOfClass"
         Case 47 : Return "eInvalidBlockName"
         Case 48 : Return "eMissingDxfField"
         Case 49 : Return "eDuplicateDxfField"
         Case 50 : Return "eInvalidDxfCode"
         Case 51 : Return "eInvalidResBuf"
         Case 52 : Return "eBadDxfSequence"
         Case 53 : Return "eFilerError"
         Case 54 : Return "eVertexAfterFace"
         Case 55 : Return "eInvalidFaceVertexIndex"
         Case 56 : Return "eInvalidMeshVertexIndex"
         Case 57 : Return "eOtherObjectsBusy"
         Case 58 : Return "eMustFirstAddBlockToDb"
         Case 59 : Return "eCannotNestBlockDefs"
         Case 60 : Return "eDwgRecoveredOK"
         Case 61 : Return "eDwgNotRecoverable"
         Case 62 : Return "eDxfPartiallyRead"
         Case 63 : Return "eDxfReadAborted"
         Case 64 : Return "eDxbPartiallyRead"
         Case 65 : Return "eDwgCRCDoesNotMatch"
         Case 66 : Return "eDwgSentinelDoesNotMatch"
         Case 67 : Return "eDwgObjectImproperlyRead"
         Case 68 : Return "eNoInputFiler"
         Case 69 : Return "eDwgNeedsAFullSave"
         Case 70 : Return "eDxbReadAborted"
         Case 71 : Return "eFileLockedByACAD"
         Case 72 : Return "eFileAccessErr"
         Case 73 : Return "eFileSystemErr"
         Case 74 : Return "eFileInternalErr"
         Case 75 : Return "eFileTooManyOpen"
         Case 76 : Return "eFileNotFound"
         Case 77 : Return "eDwkLockFileFound"
         Case 80 : Return "eWasErased"
         Case 81 : Return "ePermanentlyErased"
         Case 82 : Return "eWasOpenForRead"
         Case 83 : Return "eWasOpenForWrite"
         Case 84 : Return "eWasOpenForUndo"
         Case 85 : Return "eWasNotifying"
         Case 86 : Return "eWasOpenForNotify"
         Case 87 : Return "eOnLockedLayer"
         Case 88 : Return "eMustOpenThruOwner"
         Case 89 : Return "eSubentitiesStillOpen"
         Case 90 : Return "eAtMaxReaders"
         Case 91 : Return "eIsWriteProtected"
         Case 92 : Return "eIsXRefObject"
         Case 93 : Return "eNotAnEntity"
         Case 94 : Return "eHadMultipleReaders"
         Case 95 : Return "eDuplicateRecordName"
         Case 96 : Return "eXRefDependent"
         Case 97 : Return "eSelfReference"
         Case 98 : Return "eMissingSymbolTable"
         Case 99 : Return "eMissingSymbolTableRec"
         Case 100 : Return "eWasNotOpenForWrite"
         Case 101 : Return "eCloseWasNotifying"
         Case 102 : Return "eCloseModifyAborted"
         Case 103 : Return "eClosePartialFailure"
         Case 104 : Return "eCloseFailObjectDamaged"
         Case 105 : Return "eCannotBeErasedByCaller"
         Case 106 : Return "eCannotBeResurrected"
         Case 110 : Return "eInsertAfter"
         Case 120 : Return "eFixedAllErrors"
         Case 122 : Return "eLeftErrorsUnfixed"
         Case 123 : Return "eUnrecoverableErrors"
         Case 124 : Return "eNoDatabase"
         Case 125 : Return "eXdataSizeExceeded"
         Case 126 : Return "eRegappIdNotFound"
         Case 127 : Return "eRepeatEntity"
         Case 128 : Return "eRecordNotInTable"
         Case 129 : Return "eIteratorDone"
         Case 130 : Return "eNullIterator"
         Case 131 : Return "eNotInBlock"
         Case 132 : Return "eOwnerNotInDatabase"
         Case 133 : Return "eOwnerNotOpenForRead"
         Case 134 : Return "eOwnerNotOpenForWrite"
         Case 135 : Return "eExplodeBeforeTransform"
         Case 136 : Return "eCannotScaleNonUniformly"
         Case 137 : Return "eNotInDatabase"
         Case 138 : Return "eNotCurrentDatabase"
         Case 139 : Return "eIsAnEntity"
         Case 140 : Return "eCannotChangeActiveViewport"
         Case 141 : Return "eNotInPaperspace"
         Case 142 : Return "eCommandWasInProgress"
         Case 150 : Return "eGeneralModelingFailure"
         Case 151 : Return "eOutOfRange"
         Case 152 : Return "eNonCoplanarGeometry"
         Case 153 : Return "eDegenerateGeometry"
         Case 154 : Return "eInvalidAxis"
         Case 155 : Return "ePointNotOnEntity"
         Case 156 : Return "eSingularPoint"
         Case 157 : Return "eInvalidOffset"
         Case 158 : Return "eNonPlanarEntity"
         Case 159 : Return "eCannotExplodeEntity"
         Case 160 : Return "eStringTooLong"
         Case 161 : Return "eInvalidSymTableFlag"
         Case 162 : Return "eUndefinedLineType"
         Case 163 : Return "eInvalidTextStyle"
         Case 164 : Return "eTooFewLineTypeElements"
         Case 165 : Return "eTooManyLineTypeElements"
         Case 166 : Return "eExcessiveItemCount"
         Case 167 : Return "eIgnoredLinetypeRedef"
         Case 168 : Return "eBadUCS"
         Case 169 : Return "eBadPaperspaceView"
         Case 170 : Return "eSomeInputDataLeftUnread"
         Case 171 : Return "eNoInternalSpace"
         Case 172 : Return "eInvalidDimStyle"
         Case 173 : Return "eInvalidLayer"
         Case 180 : Return "eUserBreak"
         Case 190 : Return "eDwgNeedsRecovery"
         Case 191 : Return "eDeleteEntity"
         Case 192 : Return "eInvalidFix"
         Case 193 : Return "eFSMError"
         Case 200 : Return "eBadLayerName"
         Case 201 : Return "eLayerGroupCodeMissing"
         Case 202 : Return "eBadColorIndex"
         Case 203 : Return "eBadLinetypeName"
         Case 204 : Return "eBadLinetypeScale"
         Case 205 : Return "eBadVisibilityValue"
         Case 206 : Return "eProperClassSeparatorExpected"
         Case 207 : Return "eBadLineWeightValue"
         Case 210 : Return "ePagerError"
         Case 211 : Return "eOutOfPagerMemory"
         Case 212 : Return "ePagerWriteError"
         Case 213 : Return "eWasNotForwarding"
         Case 220 : Return "eInvalidIdMap"
         Case 221 : Return "eInvalidOwnerObject"
         Case 222 : Return "eOwnerNotSet"
         Case 230 : Return "eWrongSubentityType"
         Case 231 : Return "eTooManyVertices"
         Case 232 : Return "eTooFewVertices"
         Case 250 : Return "eNoActiveTransactions"
         Case 251 : Return "eNotTopTransaction"
         Case 252 : Return "eTransactionOpenWhileCommandEnded"
         Case 253 : Return "eInProcessOfCommitting"
         Case 254 : Return "eNotNewlyCreated"
         Case 255 : Return "eLongTransReferenceError"
         Case 256 : Return "eNoWorkSet"
         Case 260 : Return "eAlreadyInGroup"
         Case 261 : Return "eNotInGroup"
         Case 290 : Return "eInvalidREFIID"
         Case 291 : Return "eInvalidNormal"
         Case 292 : Return "eInvalidStyle"
         Case 300 : Return "eCannotRestoreFromAcisFile"
         Case 301 : Return "eMakeMeProxy"
         Case 302 : Return "eNLSFileNotAvailable"
         Case 303 : Return "eNotAllowedForThisProxy"
         Case 310 : Return "eNotSupportedInDwgApi"
         Case 311 : Return "ePolyWidthLost"
         Case 312 : Return "eNullExtents"
         Case 313 : Return "eExplodeAgain"
         Case 314 : Return "eBadDwgHeader"
         Case 320 : Return "eLockViolation"
         Case 321 : Return "eLockConflict"
         Case 322 : Return "eDatabaseObjectsOpen"
         Case 323 : Return "eLockChangeInProgress"
         Case 325 : Return "eVetoed"
         Case 330 : Return "eNoDocument"
         Case 440 : Return "eWrongCellType"
         Case 441 : Return "eCannotChangeColumnType"
         Case 442 : Return "eRowsMustMatchColumns"
         Case 433 : Return "eFileSharingViolation"
         Case 434 : Return "eUnsupportedFileFormat"
         Case 435 : Return "eObsoleteFileFormat"
         Case 500 : Return "eDwgShareDemandLoad"
         Case 501 : Return "eDwgShareReadAccess"
         Case 502 : Return "eDwgShareWriteAccess"
         Case 1001 : Return "eSecInitializationFailure"
         Case 1002 : Return "eSecErrorReadingFile"
         Case 1003 : Return "eSecErrorWritingFile"
         Case 1101 : Return "eSecInvalidDigitalID"
         Case 1102 : Return "eSecErrorGeneratingTimestamp"
         Case 1103 : Return "eSecErrorComputingSignature"
         Case 1104 : Return "eSecErrorWritingSignature"
         Case 1201 : Return "eSecErrorEncryptingData"
         Case 1203 : Return "eSecErrorDecryptingData"
         Case 20000 : Return "eInetBase"
         Case 1202 : Return "eSecErrorCipherNotSupported"
         Case 107 : Return "eWasNotErased"
         Case 208 : Return "eBadColor"
         Case 436 : Return "eFileMissingSections"
         Case 437 : Return "eRepeatedDwgRead"
         Case 503 : Return "eLoadFailed"
         Case 504 : Return "eDeviceNotFound"
         Case 505 : Return "eNoCurrentConfig"
         Case 506 : Return "eNullPtr"
         Case 507 : Return "eNoLayout"
         Case 508 : Return "eIncompatiblePlotSettings"
         Case 509 : Return "eNonePlotDevice"
         Case 510 : Return "eNoMatchingMedia"
         Case 511 : Return "eInvalidView"
         Case 512 : Return "eInvalidWindowArea"
         Case 513 : Return "eInvalidPlotArea"
         Case 514 : Return "eCustomSizeNotPossible"
         Case 515 : Return "ePageCancelled"
         Case 516 : Return "ePlotCancelled"
         Case 517 : Return "eInvalidEngineState"
         Case 518 : Return "ePlotAlreadyStarted"
         Case 519 : Return "eNoErrorHandler"
         Case 520 : Return "eInvalidPlotInfo"
         Case 521 : Return "eNumberOfCopiesNotSupported"
         Case 522 : Return "eLayoutNotCurrent"
         Case 523 : Return "eGraphicsNotGenerated"
         Case 524 : Return "eCannotPlotToFile"
         Case 525 : Return "eMustPlotToFile"
         Case 526 : Return "eNotMultiPageCapable"
         Case 527 : Return "eBackgroundPlotInProgress"
         Case 550 : Return "eSubSelectionSetEmpty" & vbCrLf & "Indicates the sub selection set is empty (contains no cells)"
         Case 600 : Return "eInvalidObjectId" & vbCrLf & "Returned when the AcDbObjectId is not valid. The object is not found in the current database."
         Case 601 : Return "eInvalidXrefObjectId" & vbCrLf & "Returned when the AcDbXrefObjectId is not valid. The object is not found in the current database, or it does not have a valid object ID and handle pair."
         Case 602 : Return "eNoViewAssociation" & vbCrLf & "Returned when there is no view association of the type requested associated with this viewport."
         Case 603 : Return "eNoLabelBlock" & vbCrLf & "Returned when there is no label block associated with this viewport."
         Case 604 : Return "eUnableToSetViewAssociation" & vbCrLf & "Returned if unable to associate the view with the viewport. An error occurred storing the view data in the database."
         Case 605 : Return "eUnableToGetViewAssociation" & vbCrLf & "Returned if unable retrieve the view associated with the viewport. An error occurred when retrieving the view data from the database."
         Case 606 : Return "eUnableToSetLabelBlock" & vbCrLf & "Returned if unable set the label block associated with the viewport. An error occurred when trying to store the label block in the database."
         Case 607 : Return "eUnableToGetLabelBlock" & vbCrLf & "Returned if unable retrieve the label block associated with the viewport. An error occurred when retrieving the label block from the database."
         Case 608 : Return "eUnableToRemoveAssociation" & vbCrLf & "Returned if unable to remove the association from the viewport."
         Case 609 : Return "eUnableToSyncModelView" & vbCrLf & "Returned if unable to sync the viewport with its associated model view."
         Case 551 : Return "eNoIntersections" & vbCrLf & "No intersections in geometric models"
         Case 1300 : Return "eNoAcDbHostApplication"
         Case 1301 : Return "eNoUnderlayHost"
         Case 0 : Return "eFailedToSetEdgeChamfers"
         Case 0 : Return "eNoConnectedBlendSet"
         Case 0 : Return "eFailedToBlend"
         Case 0 : Return "eFailedToSetEdgeRounds"
         Case 0 : Return "eFailedToSetVertexRounds"
         Case 0 : Return "eVSNotFound" & vbCrLf & "Visual style not found"
         Case 0 : Return "eVSTrue"
         Case 0 : Return "eVSFalse"
         Case 0 : Return "eVSAlreadyExists"
         Case 0 : Return "eVSOneOffCreated"
         Case 0 : Return "eVSAPIOnlyValues"
         Case 0 : Return "eEmbeddedIntersections"
         Case 528 : Return "eNotShownInPropertyPalette"
         Case 304 : Return "eNotClonedPrimaryProxy"









            ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
         Case Else
            Return ""
      End Select
   End Function

   Public Shared Function GetMapErrText(ByVal iErrCode As Integer) As String
      Select Case iErrCode



         Case 0 : Return "General ADE return value: call to ADE object is not successful."
         Case 1 : Return "Invalid function argument."
         Case 2 : Return "BadInput"
         Case 3 : Return "ObjectNotFound"
         Case 4 : Return "OutOfMemory"
         Case 5 : Return "Object Not Initialized"
         Case 6 : Return "WrongType"
         Case 7 : Return "WrongProject"
         Case 8 : Return "Invalid function argument type."
         Case 9 : Return "ADSError"
         Case 10 : Return "AdsNameConvertionFails"
         Case 11 : Return "WrongArgument"
         Case 12 : Return "WriteBufFails"
         Case 13 : Return "ReadBufFails"
         Case 14 : Return "XDataCorrupted"
         Case 15 : Return "NoEnvironment"
         Case 16 : Return "UsrBreak"
         Case 17 : Return "Uncomparable"
         Case 18 : Return "Permission Denied. No permission to perform some action. When using the following commands, the message has different meanings: ADESAVEOBJS = can't be executed in demonstration mode; ADEDRAWINGS = User has no rights to update the set; ADESELOBJS, ADDREMOBJS = User has no rights to edit; ADEDWGMAINT = User needs to be superuser to remove the foreign locks; MAPOPTIONS: System Preferences = can't set ""Force User Login"" flag and change ""Object Locking"" flag if drawing set contains active or locked drawings. Deactivate or unlock the drawings before trying to set these preferences."
         Case 19 : Return "WrongSyntax"
         Case 20 : Return "Duplicate"
         Case 21 : Return "InvalidPathOrFileName"
         Case 22 : Return "InvalidVersion"
         Case 23 : Return "FileIOFatalError"

            '    External(Subsystems)
         Case 200 : Return "AcDbError"
         Case 201 : Return "IRDNotInitialized"
         Case 202 : Return "IRDError"
         Case 203 : Return "ASENotInitialized"
         Case 204 : Return "ASEError"
         Case 205 : Return "ASIError"
         Case 206 : Return "AsiNotInitialized"
         Case 207 : Return "AsiConnectToEnvironmentFailed"

            '   Transactional(Manager)
         Case 1000 : Return "Closed. Repeated attempts to close previously closed ADE object. Call support."
         Case 1001 : Return "WasErased. Attempt to work with erased ADE object. Call support."
         Case 1002 : Return "OpenForRead. Attempt to update ADE objects opened for read. Call support."
         Case 1003 : Return "OpenForWrite. Attempts to get multiple access to ADE object opened for write. Call support."
         Case 1004 : Return "WrongMode. Incorrect mode of the ADE objects should be opened. Call support."
         Case 1005 : Return "Clone. Exception at the time of cloning ADE objects. Call support."
         Case 1006 : Return "Response. Incorrect attempt to start ADE transaction. Call support."
         Case 1007 : Return "ObjIsAbsent. Attempt to work with erased ADE object. Call support."
         Case 1008 : Return "Access. Type of work with ADE does not correspond to its status. Call support."
         Case 1009 : Return "MultipleUsage. Attempts to get multiple access to ADE object opened for write. Call support."
         Case 1010 : Return "Upgrade. Incorrect attempt to update opening mode of the ADE object. Call support."
         Case 1011 : Return "NotClosed. Object was not closed during current ADE transaction. Call support."


            '  CAdeList 
         Case 1100 : Return "GetIteratorFails"
         Case 1101 : Return "ListIsEmpty"

            '  CAdeListIterator 
         Case 1102 : Return "ListEnd"
         Case 1103 : Return "ListObjectIsAbsent"


            '   Drawing 
         Case 1200 : Return "QueriedEntity Ignoring queried entity for saving selection. When using ADESAVEOBJS, the message means queried objects that are selected for save back are ignored."
         Case 1201 : Return "DwgNotActive Attempt to read the object locked from an inactive drawing. When using ADEWHOHASIT, the message means the drawing from which the object was queried is no longer active. ADE is unable to determine if the object selected is currently locked. Activate the specified drawing and reentert the command."
         Case 1202 : Return "ReadDwgFileFails ADE fails to read external drawing. If using ADEDRAWINGS, this message means that ADE is unable to read the specified drawing. Perhaps the drawing doesn't exit or the specified file is not a valid AutoCAD Drawing File. Check the error message stack for more information."
         Case 1203 : Return "MultipleUsers ADE fails to access external drawing.. If using ADEDRAWINGS, this message means ADE is unable to access the specified drawing because of file locking problems. Check the error message stack for more information."
         Case 1204 : Return "EntityLockingFails ADE fails to lock. If using ADESELOBJS, this message means ADE is unable to lock an object. The object may already be locked. Use the ADEWHOHASIT to determine if the object is locked, perhaps by another user. Check the error message stack for more information."
         Case 1205 : Return "UnlockedEntity Entity is unlocked by another ADE user. If using ADEWHOHASIT, this message indicates that the selected object is not currently locked."
         Case 1206 : Return "LockedEntity Entity has been locked by another ADE user. If using ADESELOBJS, this message indicates that the object is already locked by another user. Use the ADEWHOHASIT command to identify the user."
         Case 1207 : Return "AlreadyInSaveSet"
         Case 1208 : Return "AlreadyNotInSaveSet"
         Case 1209 : Return "MultipleReaders"
         Case 1210 : Return "OpenPrefDictionaryFails ADE fails to open ADE preferences dictionary. Call support."
         Case 1211 : Return "SavePrefDictionaryFails ADE fails to save ADE preferences dictionary. Call support."
         Case 1212 : Return "RestoreDSetFails ADE fails to restore the drawing set. Call support."
         Case 1213 : Return "OpenDSetDictionaryFails ADE fails to open ADE drawing set dictionary. Call support."
         Case 1214 : Return "SaveDSetDictionaryFails ADE fails to save ADE drawing set in dictionary. Call support."
         Case 1215 : Return "OpenQueryDictionaryFails ADE fails to open ADE query library dictionary. Call support."
         Case 1216 : Return "SaveQueryDictionaryFails ADE fails to save ADE query library in dictionary. Call support."
         Case 1217 : Return "OpenRTableDictionaryFails ADE fails to open ADE range table dictionary. Call support."
         Case 1218 : Return "SaveRTableDictionaryFails ADE fails to save ADE range table in dictionary. Call support."
         Case 1219 : Return "RestoreRTableDictionaryFails ADE fails to restore ADE range table in dictionary. Call support."
         Case 1220 : Return "OpenDocViewDictionaryFails ADE fails to open ADE Doc View information dictionary. Call support."
         Case 1221 : Return "SaveDocViewDictionaryFails ADE fails to save ADE Doc View information in dictionary. Call support."
         Case 1222 : Return "OpenKeyViewDictionaryFails ADE fails to open ADE Key View information dictionary."
         Case 1223 : Return "SaveKeyViewDictionaryFails ADE fails to save ADE Key View information in dictionary. Call support."
         Case 1224 : Return "SaveProjectionFails ADE fails to save projection code in the drawing. Call support."
         Case 1225 : Return "CopyHardPointerFails ADE fails to apply property alteration for some symbol table. Call support."
         Case 1226 : Return "DwgToBeReloaded"
         Case 1227 : Return "DwgHasBeenModified There were objects queried from the drawing that will be treated as new objects. If using ADEDRAWINGS, this message means that when a drawing from which objects have been queried is detached, ADE converts the objects into newly created objects. When you use the ADEWHOHASIT command to see the origin of these objects, it says that they have not been queried."
         Case 1228 : Return "OnLockedLayer Objects from a locked layer have been selected. If using ADESELOBJS, ADEREMOBJS, or ADESAVEOBJS, this message means you selected objects from a locked layer and they cannot be added to, saved to. or removed from the the save set or saved to source."
         Case 1229 : Return "DwgSaveFales ADE fails to save the source drawing. If using ADESAVEOBJS, ADESELOBJS, ADEREMOBJS, OPEN, NEW, or QUIT, or if you're configuring options, or modifying objects, you may get this message. Call support. NOTE: Use this message exactly as spelled here."
         Case 1230 : Return "DwgLocksLeft ADE fails to remove object locks (if present) by the end of ADE session. If using OPEN, NEW, or QUIT, or if you're configuring options, this message means the drawing might be locked by another ADE user."
         Case 1231 : Return "LinkWillBeLost ADE does not save links between queried objects and source drawings between ADE sessions. Detach source drawing with queried objects; Use the SAVE command with queried objects or no objects in the save set."
         Case 1232 : Return "DwgDiskFull"
         Case 1233 : Return "DwgHasQueriedObject"
         Case 1234 : Return "UnlockedFile"

            '     Current Session 
         Case 1300 : Return "GetCPointFails  ADE fails to get Text location for the entity. Call support."
         Case 1301 : Return "SetCPointFails ADE fails to store Text location for the entity. Call support."
         Case 1302 : Return "TextInsPointMissed Missing Text insert point. Call support."
         Case 1303 : Return "TextAllignPointMissed Missing alignment point for Aligned and Fit Text. Call support."
         Case 1304 : Return "TextHeightMissed Missing Text height. Call support."
         Case 1305 : Return "TextStringMissed Missing Text string. Call support."
         Case 1306 : Return "IndexUpdateFails Exception in Index generation or regeneration. If using ADESAVEOBJS, ADESELOBJS, ADEREMOBJS, or ADEDWGMAINT, this message means entity modification occurred. Call support."
         Case 1307 : Return "IgnorePreview ADE custom object is selected to add to save set or to save. If using ADESAVEOBJS, ADESELOBJS, or ADEREMOBJS this message has the following meaning: When doing a Preview Query, ADE creates a special object called a PREVIEW object, used to display the queried objects. PREVIEW cannot be saved back to a source drawing. When a user selects this object for adding to the save set or when saving back, ADE detects this and prevents the operation."
         Case 1308 : Return "IgnorePSpace"
         Case 1309 : Return "EraseIRDObjectFails ADE fails to erase the Object Data Table. Call support."
         Case 1310 : Return "RenameIRDObjectFails ADE fails to rename the Object Data Table. Call support. If using ADEDEFDATA, this message means ADE can't rename Object Data Table. Perhaps Object Data of the same name already exists in the drawing or Object Data Table definitions bearing the old name are different in the source drawings. Check the error message for more information."
         Case 1311 : Return "AlterIRDObjectFails ADE fails to alter Object Data Table. If using ADEDEFDATA, this message means ADE can't alter Object Data Table. Perhaps Object Data Table definitions are different in the source drawings. Check the error message stack for more information."
         Case 1312 : Return "IrdDuplicateTableName Object Data Table with specified name already exists. ADEDEFDATA - all Object Data table names must be unique. Duplicate names are not allowed."
         Case 1313 : Return "IrdNotIdenticaFormat Conflict in Object Data Table definition. If using ADEDEFDATA, this message means that perhaps Object Data Table definitions are different in the source drawings. NOTE: Use this message exactly as spelled here."
         Case 1314 : Return "BHatchUnit ADE treats bhatch and its boundary as one unit. If using ADESELOBJS or ADEREMOBJS, this message has the following meaning: When adding an object to the save set, ADE checks if this object is part of a hatch boundary. If it is, all other objects that form the boundary are added to or removed from the save set. When saving back bhatched areas, ADE always treats the boundary as one object."
         Case 1315 : Return "ReQuery ADE queried one or more objects twice. ADE does not support UNDO for this operation. If using ADEQUERY or ADERUNXQUERY this message has the following meaning: If a drawing file has been modified by another ADE user and if a queried object matches another query, ADE removes the old copy and queries a new copy. This operation can't be undone."
         Case 1316 : Return "CantAccessFont"
         Case 1317 : Return "CantAccessImageFile"
         Case 1318 : Return "UnableRedefineXrefBlock"


            ''Drawing Set
         Case 1500 : Return "ADE fails to read Drawing Set from DWG file. You encounter this message during ADE initialization or when using Open drawing file or ADEDRAWINGS. If using ADEDRAWINGS - attach drawing, the message means ""activate on attach"" is ON or ade_dsattach(), ade_dswcattach() drawing is corrupted or old ADE version is in use."
         Case 1501 : Return "DuplicatedDrawing Attempt to attach the same drawing twice. If using ADEDRAWINGS, this error appears when a drawing with the same name has already been attached to the work session."
         Case 1502 : Return "NestedDrawing Prohibited attempt to edit properties of the drawing in the nested drawing set. If using ADEDRAWINGS, this message means a user is not allowed to modify the transformation and save back extents of nested drawings in the work session. These properties can only be modified for top level drawings."
         Case 1503 : Return "ActivateDrawingFails ADE fails to activate source drawing. ADE was unable to activate a drawing Perhaps the drawing does not exist or it is locked by another user, or the current user doesn't have permission to read the specified drawing file. Check the error message stack for more information."
         Case 1504 : Return "DeactivateDrawingFails ADE fails to deactivate source drawing. ADE is unable to deactivate a drawing. Perhaps the drawing is locked by another user, the drawing no longer exists, or there are locked objects in the drawing. Check the error message stack for more information."
         Case 1505 : Return "LongDrawingDescription Specified drawing description exceeds 133 symbols. Shorten description."
         Case 1506 : Return "EntityHasBeenLocked Drawing with locked entities can't be deactivated. ADEDRAWINGS - the specified drawing cannot be deactivated because it contains locked objects. Remove locks and deactivate."
         Case 1507 : Return "PreviewNotSupported ADE 2.0 ignoresTolerance, Body,Ellipse, 3dSolid, Region and Mline. If using ADEQUERY (Preview), ADEQVIEWDWGS, or ADEKEYVIEW, this message means ADE does not support Preview Query of Tolerance, Body,Ellipse, 3dSolid, Region and Mline."
         Case 1508 : Return "AliasIsInUse A drive alias of the same name already exists."
         Case 1509 : Return "ActivateDrawingCancelled AcMapDrawingSetReactor::DrawingToBeActivated returns Adesk::kFalse, the attach operation is cancelled, and the error is returned to the application to handle."
         Case 1510 : Return "AttachDrawingCancelled AcMapDrawingSetReactor::DrawingToBeAttached returns Adesk::kFalse, the attach operation is cancelled, and the error is returned to the application to handle."


            '  Feature Alteration 
         Case 1800 : Return "InvalidFeatureType Attempt to set an invalid property alteration type. If calling API functions ade_altpsetprop or ade_altpdefine, check for a mistake in property type."
         Case 1801 : Return "NoListId Property alteration internal list is invalid. Call support."
         Case 1802 : Return "InvalidExpType Attempt made to set an invalid property alteration expression type. Call support."
         Case 1803 : Return "NoExpression Property alteration internal object is invalid. Call support."
         Case 1804 : Return "TextCreationFailed Property alteration was unable to create a new text object. This message occurs when using queries that alter properties. Check expressions in the text property alteration definition."
         Case 1805 : Return "HatchCreationFailed Property alteration was unable to create a new hatch object. This message occurs when using queries that alter properties. Check expressions in the hatch property alteration definition."
         Case 1806 : Return "InvalidColor. Invalid color passed to property alteration. This message occurs when using queries that alter properties. Check expressions evaluates to a valid AutoCAD color."
         Case 1807 : Return "InvalidLayer. Invalid layer name. This message occurs when using queries that alter properties. Check expressions evaluates to a valid AutoCAD layer."
         Case 1808 : Return "InvalidStyle Invalid style name. This message occurs when using queries that alter properties. Check expressions evaluates to a valid style."
         Case 1809 : Return "InvalidJustification The expression for justification in a text property alteration did not evaluate to a valid justification. This message occurs when using queries that alter properties. Check expressions evaluates to a valid AutoCAD justification."
         Case 1810 : Return "InvalidScale"
         Case 1811 : Return "NoRangeId ADE internal object is invalid. Call support."


            '  Mapping 
         Case 1900 : Return "MapCoincPoint Coincident points. If using ADERSHEET or ADETRANSFORM this message means either old or new points are coincident. They must be different."
         Case 1901 : Return "MapWrongScale Invalid scale. Call support."
         Case 1902 : Return "MapTransform Can't transform entity. ADERSHEET, ADETRANSFORM, ADEQUERY, ADESAVEOBJS An error appeared at the time of entity transformation. It is high-level error. There must be another error in the stack with more specific information."
         Case 1903 : Return "MapWrongExtents Invalid entity extents. If you're using ADETEXTLOC, ADERSHEET, ADEQUERY, ADESAVEOBJS, or calling AcDbEntity::getGeomExtents() function you may get this message."
         Case 1904 : Return "MapWrongPoints Invalid points number. If you're using ADERSHEET, this message means that the numbers of old and new points are different, or less than 2. Dialog doesn't allow this. C."
         Case 1905 : Return "MapWrongSelSet Invalid selection set. Call support."
         Case 1906 : Return "MapWrongEntityName Invalid entity name. The entity is open. For example, it has been received from the API."
         Case 1907 : Return "MapOpenEntity Can't open entity. The entity is open. For example, another application opened the entity."
         Case 1908 : Return "MapUpgradeEntity Can't upgrade open. Entity modification occured."
         Case 1909 : Return "MapMoveStretchPoints Can't modify stretch points. Call support."
         Case 1910 : Return "MapEntityPoint Can                                                               't modify entity points. Call support."
         Case 1911 : Return "MapCmdecho Can't change CMDECHO variable. Using ADEFILLPOLYG may produce this message."
         Case 1912 : Return "MapCecolor  Can't change CECOLOR variable. Using ADEFILLPOLYG may produce this message."
         Case 1913 : Return "MapHatch Error in hatch command. Using ADEFILLPOLYG may produce this message."
         Case 1914 : Return "MapWrongIntersectForPoints Can't find intersection. Using ADEQUERY or calling AcDbentity::IntersectWith() function may produce this message."
         Case 1915 : Return "MapWrongHandle Wrong entity handle. Call support."
         Case 1916 : Return "MapNotPolyline Entity isn't polyline. Call support."
         Case 1917 : Return "MapIterator Can't create iterator. Call support."
         Case 1918 : Return "MapWriteXData Can't write Xdata. Ensure that Xdata size is 16 KB or less."
         Case 1919 : Return "MapBuffer Can't create buffer. If you're using ADEQUERY, to make a location query using a bufferfence, you may get this message."
         Case 1920 : Return "MapStretchPoints  Can't get stretch points. If you're using ADETRANSFORM or ADEQUERY or calling AcDbEntity::getStretchPoints() you may get this message."


         Case 2000 : Return "Invalid topology name. Occurs during topology creation."
         Case 2001 : Return "Topology already exists. Occurs during topology creation."
         Case 2002 : Return "Error building network topology. Occurs during topology creation."
         Case 2003 : Return "Error building polygon topology. Occurs during topology creation."
         Case 2004 : Return "Can't create node. Occurs during topology creation."
         Case 2005 : Return "Can't create link. Occurs during topology creation."
         Case 2006 : Return "Can't create centroid. Occurs during topology creation."
         Case 2007 : Return "Can't register topology API. Occurs during ADE loading."
         Case 2008 : Return "Function isn't available. Occurs if you're using topology functions of the API."
         Case 2009 : Return "Error writing Xdata. Occurs during topology creation and modification."
         Case 2010 : Return "Topology doesn't exist. Occurs if you're using topology functions of the API."
         Case 2011 : Return "Wrong overlay type."
         Case 2012 : Return "Can't create new layer. Using ADEDWGCLEAN produces this message."
         Case 2013 : Return "Block doesn't exist."
2014:       Return "Topology isn't open for write. Occurs when editing topology."
         Case 2015 : Return "Can't open object data table. Occurs when loading and editing topology."
         Case 2016 : Return "Invalid object data table. Occurs when loading and editing topology."
         Case 2017 : Return "Topology is already loaded. Occurs when loading topology."
         Case 2018 : Return "Incomplete toplogical element. Occurs when editing topology."
         Case 2019 : Return "Invalid color number. Occurs when using ADEDWGCLEAN and creating topology."
         Case 2020 : Return "Invalid flag. Occurs when using ADEDWGCLEAN."
         Case 2021 : Return "Invalid tolerance. Occurs when using ADEDWGCLEAN and creating topology."
         Case 2022 : Return "Invalid corridor width. Occurs when using ADEDWGCLEAN."
         Case 2023 : Return "Invalid offset. Occurs when using buffering."
         Case 2024 : Return "Invalid marker height. Occurs when using ADEDWGCLEAN."
         Case 2025 : Return "Invalid marker type. Occurs when using ADEDWGCLEAN."
         Case 2026 : Return "Invalid type for new entities. Occurs when using ADEDWGCLEAN."
         Case 2027 : Return "Invalid error type. Occurs when using ADEDWGCLEAN."
         Case 2028 : Return "Intersections detected. Occurs when creating and editing polygon topology."
         Case 2029 : Return "Can't overlay topology with itself."
         Case 2030 : Return "Can't access source drawing."
         Case 2031 : Return "Source drawing isn't active."
         Case 2032 : Return "Can't access source drawing database."
         Case 2033 : Return "Can't get object ID by handle in source drawing database."
         Case 2034 : Return "Topology isn't loaded."
         Case 2035 : Return "Node object doesn't exist in node topology."
         Case 2036 : Return "Wrong node coordinates."
         Case 2037 : Return "Node isn't referenced in links."
         Case 2038 : Return "Link references nonexistent node."
         Case 2039 : Return "Link has invalid ID at the start node."
         Case 2040 : Return "Link has invalid ID at the end node."
         Case 2041 : Return "Wrong centroid coordinates."
         Case 2042 : Return "Link has invalid ID for the left polygon."
         Case 2043 : Return "Link has invalid ID for the right polygon."
         Case 2044 : Return "Centroid isn't inside polygon."
         Case 2045 : Return "Polygon has several centroids inside."
         Case 2046 : Return "Some polygons are incorrect."
         Case 2047 : Return "Incorrect polygon area."
         Case 2048 : Return "Incorrect polygon perimeter."
         Case 2049 : Return "Topology loaded from source drawings can't be open for write."
         Case 2050 : Return "Temporary topology can't be open for write."
         Case 2051 : Return "Current drawing doesn't have OD table with information about last ID."
         Case 2052 : Return "Can't create or load empty topology."
         Case 2053 : Return "Topological objects were modified by AutoCAD commands."
         Case 2054 : Return "Object belongs to multiple topologies and can't be erased."
         Case 2055 : Return "Can't calculate offset. Use default. Occurs when using buffering."
         Case 2056 : Return "Zero offset. Can't build buffer."
         Case 2057 : Return "Offset has different sign for some objects. Can't build buffer."
         Case 2058 : Return "Invalid selection set. Occurs when using the API."
         Case 2059 : Return "Cleadup model isn't initialized. Occurs when using the API."
         Case 2060 : Return "There is no current group. Occurs when using the API."
         Case 2061 : Return "Invalid error index. Occurs when using the API."
         Case 2062 : Return "Current error isn't set. Occurs when using the API."
         Case 2063 : Return "Link doesn't exist in tracing model. Occurs when using the API."
         Case 2064 : Return "Node doesn't exist in tracing model. Occurs when using the API."
         Case 2065 : Return "Result path isn't calculated. Occurs when using the API."
         Case 2066 : Return "Invalid element index. Occurs when using the API."
         Case 2067 : Return "Can't process ADE expression. Occurs when using overlay, buffer, dissolve, or tracing command."
         Case 2068 : Return "Can't write into topology OD table. Occurs when using dissolve command."
         Case 2069 : Return "Can't create OD table. Occurs when using topology creation, overlay, buffer, or dissolve commands."
         Case 2070 : Return "Can't add column to OD table. Occurs when using topology creation, overlay, buffer, or dissolve commands."
         Case 2071 : Return "Start and end nodes are the same. Occurs doing shortest path tracing."
         Case 2072 : Return "Empty path. Occurs during shortest path tracing."
         Case 2073 : Return "Empty path. Occurs when tracing floods."
         Case 2074 : Return "Can't rename topology, because current drawing has queried objects with OD."
         Case 2075 : Return "Can't delete topology, because current drawing has queried objects with OD."
         Case 2076 : Return ""
            ' Topology API 
         Case 2100 : Return "TopApiErrWrongInput Missing or invalid parameter."
         Case 2101 : Return "TopApiWrongId Invalid ID."

            ' Tracing 
         Case 2150 : Return "TopSprErr"

            '  Query Definition 
         Case 2200 : Return "UnexpectedBuffChar  Invalid character encountered while reading the query definition from the drawing. Options are a) Recover the drawing b) Define and save a new query definition in the drawing."
         Case 2201 : Return "InvalidIndex An invalid line number was specified for either grouping or ungrouping of query lines. Specify the correct line number for grouping or ungrouping the lines."
         Case 2202 : Return "InvalidQueryLine One or more query lines have been incorrectly defined. May occur when you incorrectly place a parenthesis or an operator in a query line."
         Case 2203 : Return "InvalidName Either a query or a query category name is invalid. Ensure that the query or category name conform to the AutoCAd symbol name specifications."
         Case 2204 : Return "EntryAlreadyExists Either the query or the query category name already exists in the query library. Ensure that the query name is unique within the query library."
         Case 2205 : Return "EntryInOtherCategory The query name specified already exists in another category in the query library. Ensure that the query name is unique within the query library."
         Case 2206 : Return "EntryAndFileAlreadyExist The file name specified for saving the external query already exists. Choose a different file name."
         Case 2207 : Return "ASIConnectFailed The connection to the ASI environment required for the SQL query was not made. Use ASE to connect to the environment before attempting to perform the SQL query."
         Case 2208 : Return "ASIStmtPrepareFailed The call to CAsiExecStm:: Prepare failed. correct the table name or the SQL statement specified."
         Case 2209 : Return "ASICsrAllocFailed The call to CAsiCsr::Allocate failed. Look at the ASI error displayed."
         Case 2210 : Return "ASICsrOpenFailed The call to CAsiCsr::Open failed. Look at the ASI error displayed."
         Case 2211 : Return "InvalidDOName An invalid Environment, Schema or Catalog name was specified. Set the correct Environment, Catalog, and Schema names."
         Case 2212 : Return "LPInitFailed The call to CAseLinkPath::init failed. Look at the ASE error displayed."
         Case 2213 : Return "ColNotFound Used for the SQL Order-by dialog now obsolete. Call support."
         Case 2214 : Return "QDefNotInTM The CAdeQueryDef object was not appended to the Transaction Manager. Internal error."
         Case 2215 : Return "QryDefnExists A query definition already exists and a new one cannot be loaded. Clear the existing query definition before loading a new one."
         Case 2216 : Return "InvalidOperator Invalid operator defined in query definition. The specified comparison operator is incompatible with operand types. Do not use > with the point type. Check the query definition and change either the operator or operand type."
         Case 2217 : Return "InvalidPtrnOperator Invalid operator defined in query definition for pattern value. If value operand is defined as pattern, only "" = "" comparison operator can be used. Check the query definition and change either operator or operand value."
         Case 2218 : Return "InvalidField Non-existent object data field specified. This error occurs when the user specifies the wrong object data field name for a table (if there is no such field in the specified table) in the query definition and executes the query. Check query definition and tables and correct the mistake."
         Case 2219 : Return "InvalidNotBranch"
         Case 2220 : Return "InvalidBranch"
         Case 2221 : Return "UndefinedValue"
         Case 2222 : Return "InvalidLocationType"
         Case 2223 : Return "CantLoadExternQuery"

            'Query Manager 
         Case 2300 : Return "IntersectFailed A call to CAseLinkSel:: intersectPartialKey failed. Look at the ASE error displayed."
         Case 2301 : Return "NoTemplate The query type was specified as report but no report options were defined. Define report options."
         Case 2302 : Return "ASIStoreValueFailed A call to CAsiData ::storeValue failed. Look at the ASI error displayed."
         Case 2303 : Return "ASIGetValueFailed A call to CAsiData ::getValue failed. Look at the ASI error displayed."


            '  Utility 
         Case 2400 : Return "LicFatal Fatal error in ADE license. Call support."
         Case 2401 : Return "FileNotFound Can't find associated document. Occurs when using ADEDOCVIEW."
         Case 2402 : Return "PathNotFound Can't find executable file. Occurs when using ADEDOCVIEW."
         Case 2403 : Return "BadFormat Syntax error in the command line. Occurs when using ADEDOCVIEW."
         Case 2404 : Return "ConvtErr Error converting ADE 1.0 data to ADE 2.0 data. Occurs when using ADECONVERT."

            ' Data Dialogs 
         Case 2450 : Return "IRDMismatch"
         Case 2451 : Return "IRDInvalidName"
         Case 2452 : Return "IRDTableExists"
         Case 2453 : Return "InvalidTableName"
         Case 2454 : Return "InvalidAttrName"
         Case 2455 : Return "TopoName"
         Case 2456 : Return "QueriedAndNotNew"
         Case 2457 : Return "NotAdministrator"

            '  GenLink 
         Case 2500 : Return "TagNotFound"
         Case 2501 : Return "TagValueAbcent"
         Case 2502 : Return "IllegalFormat"
         Case 2503 : Return "ColMoreThanOne"

            ' Environment 
         Case 2600 : Return "InitEnv An error occurred during the initialization of ADE. The cause of this error may be due to errors in loading/initializing ADE user preferences, system preferences, log file, or user list."
         Case 2601 : Return "CantFindAdeExePath"
         Case 2602 : Return "INIWrite"
         Case 2603 : Return "InvalidUserName The user name specified does not exist in the user list. Use a user name that already exists in the user list or define a new one using User Administration."
         Case 2604 : Return "LoadUserList"
         Case 2605 : Return "SaveUserList"
         Case 2606 : Return "InvalidPswd The password specified does not match the one specified in the user list for this user. Use the correct password."

            'Rx 
         Case 2700 : Return "RxAseLoad ASE isn't loaded Can't initialize ASE API."
         Case 2701 : Return "RxAseInit Object Data module isn't loaded."
         Case 2702 : Return "RxIrdLoad(Can) 't initialize Object Data API."
         Case 2703 : Return "RxIrdInit Specified Coord system category not found in the library. Call support."

            ' Projection 
         Case 2800 : Return "NoProjCatFound Specified Coord system category not found in the library.Call support."
         Case 2801 : Return "NoDatumFound Specified Coord system datum not found. Call support."
         Case 2802 : Return "NoElipFound Ellipsoid not found in the ellipsoid list. Call support."
         Case 2803 : Return "NoCoordFound Specified Coord Sys not found. Call support."
         Case 2804 : Return "FaileOpenDatumFile(Can) 't open projection .mp3 file. Occurs when loading ADE."
         Case 2805 : Return "FaileOpenElipFile(Can) 't open ellipse file. Occurs when loading ADE."
         Case 2806 : Return "NoneCoord Internal code to set ""None"" projection to the drawing. Call support."


            'Expression 
         Case 2900 : Return "NoExpressionFound Empty expression is specified. Call support."
         Case 2901 : Return "GetPropFail This is an internal code to show that entity has no specified property. Call support."
         Case 2902 : Return "ExpEvalFail ADE fails to evaluate expression. Occurs when executing query with property alteration and executing a property query."
         Case 2903 : Return "ExpMissingQuote Quotes mismatched in SQL expression. Occurs when executing a SQL query and a query with SQL property alteration. Also occurs when using ADECONVERT."
         Case 2904 : Return "ExpMissingCParen Parenthesis mismatched. Occurs when executing a query with feature alteration and executing a property query."
         Case 2905 : Return "ExpExceedThreeOper More than three operands are specified. Occurs when executing a query with property alteration and executing a property query."
         Case 2906 : Return "RngTabNameExist Range table with specified name already exists. Call support."
         Case 2907 : Return "LpnInvalid"
         Case 2908 : Return "LpnNotFound"
         Case 2909 : Return "RangeInvalidElse"


            ' Index 
         Case 3000 : Return "InvalidIndexVersion The version of the index in the drawing is invalid. The options are: 1)Regenerate the index using drawing maintenance 2)Remove the index using the index removal utility and then re-generate the index."
         Case 3001 : Return "IndexOutOfDate The index in the drawing is out-of- date. Regenerate the index using drawing maintenance."
         Case 3002 : Return "TypeAllObjects"
         Case 3003 : Return "TypeNoOneObject"

            ' Validation
         Case 3100 : Return "WrongSymbolName"
         Case 3101 : Return "WrongSymbol"
         Case 3102 : Return "WrongStrLength"
         Case 3103 : Return "DirDoesNotExist"
         Case 3104 : Return "DirReadOnly"
         Case 3105 : Return "AccessDenied"
         Case 3106 : Return "FileDoesNotExist"
         Case 3107 : Return "FileAlreadyExists"
         Case 3108 : Return "FileOpenFailed"
         Case 3109 : Return "FileReadOnly"
         Case 3110 : Return "InvalidString"
         Case 3111 : Return "OutOfRange"
         Case 3112 : Return "WrongColor"
         Case 3113 : Return "IncorrectParameters One of ADE validation functions recognized incorrect input parameters. This error is an internal ADE error."
         Case 3114 : Return "FileOpenLimit"
         Case 3115 : Return "ShareViolation"
         Case 3116 : Return "NetAccessDenied"
         Case 3117 : Return "PathDoesNotExist"

            ' File Locking 
         Case 3200 : Return "DwkFileDoesNotExist ADE lock file is locked. Occurs when using ADEDRAWINGS and ADEQUERY commands and when ADE is running in a multi-user environment."
         Case 3201 : Return "OpenDwkFileFailed ADE was unable to open the .DWK lock file. Call support."
         Case 3202 : Return "FileLockedByAcad Attempt to remove a user who does not exist from the lock file. Call support."
         Case 3203 : Return "OldMapLockFile ADE was unable to create the .DWK lock file. Call support."
         Case 3204 : Return "FileIsNotDwk ADE tried to lock a file for write that was already locked for read. Call support."
         Case 3205 : Return "SpecifiedUserDoesNotExist ADE tried to lock a file for read that was already locked for write. Occurs during query operations in a multi-user environment."
         Case 3206 : Return "CreateDwkFileFailed ADE tried to open and read a file that was not a valid .DWK file. Call support."
         Case 3207 : Return "FileIsLockedForRead ADE was unable to unlock the lock file. Call support."
         Case 3208 : Return "FileIsLockedForWrite ADE tried to attach a file that is already open by AutoCAD. Occurs when using ADEDRAWINGS with ATTACH operations if the file is open in an AutoCAD project."
         Case 3209 : Return "InvalidLockStateSpecified ADE internal object is invalid. Call support."
         Case 3210 : Return "NotOwnerOfWLH ADE tried to remove a write lock when the user did not have a write lock. Call support."
         Case 3211 : Return "UserIsNotWriter"
         Case 3212 : Return "UserIsNotReader"
         Case 3213 : Return "UserHasReadLock"
         Case 3214 : Return "LockFileIsFull"
         Case 3215 : Return "DwgFileDoesNotExist ADE tried to unlock a file but the .DWK file was missing. Occurs if the .dwk file was erased after a file was attached."
         Case 3216 : Return "NotAnADELockFile ADE internal object is invalid. Call support."
         Case 3217 : Return "FileMayHaveBeenModified Existing .DWK file does not belong to ADE. the lock file exists and can be read by ADE, but ADE does not own the file."
         Case 3218 : Return "FileHasLocks ADE tried to remove a lock file but it was not found. Occurs if the .dwk file was erased after a file was attached."

            '  Unicode Support 
         Case 4000 : Return "UnicodeInsufficientBufferToConvert"
         Case 4001 : Return "UnicodeInvalidFlagsToConvert"
         Case 4002 : Return "UnicodeInvalidParameterToConvert"
         Case 4003 : Return "UnicodeNoTranslation"
         Case 4004 : Return "UnicodeCodePageNotAvailable"

            'Double-Byte Support
         Case 4005 : Return "NoMBCSAllowed"


         Case Else
            Return GetAcadErrText(iErrCode)
      End Select
   End Function
   Public Shared Sub ShowAcadError(ByVal iErrCode As Integer, ByVal bMsgBox As Boolean, ByVal sTitle As String)

      If bMsgBox Then
         System.Windows.Forms.MessageBox.Show("Error Code: " & CStr(iErrCode) _
  & vbCrLf & GetAcadErrText(iErrCode), sTitle)
      Else
         AcadDocument.WriteMessage(sTitle & " - Error Code: " & CStr(iErrCode) & vbCrLf & GetAcadErrText(iErrCode))
      End If
   End Sub
   Public Shared Sub ShowMapError(ByVal iErrCode As Integer, ByVal bMsgBox As Boolean, ByVal sTitle As String, Optional ByVal sAddInfo As String = "")
      If sAddInfo.Length <> 0 Then sAddInfo &= vbCrLf

      If bMsgBox Then
         System.Windows.Forms.MessageBox.Show("Error Code: " & CStr(iErrCode) _
  & vbCrLf & GetMapErrText(iErrCode), sTitle)
      Else
         AcadDocument.WriteMessage(sTitle & " - Error Code: " & CStr(iErrCode) & vbCrLf & GetMapErrText(iErrCode))
      End If
   End Sub
   Public Shared Sub GetMapEx(ByVal oSysEx As System.Exception, ByVal bMsgBox As Boolean, Optional ByVal sTitle As String = "")
      Dim oMapEx As Autodesk.Gis.Map.MapException
      Dim oMapTopoEx As Autodesk.Gis.Map.MapTopologyException
      Dim sMsg As String
      Dim iErrCode As Integer
      If sTitle.Length = 0 Then sTitle = "e300"

      Try
         Dim sType As String = oSysEx.GetType().ToString()
         Select Case sType
            Case "Autodesk.Gis.Map.MapException"
               oMapEx = DirectCast(oSysEx, Autodesk.Gis.Map.MapException)
               sMsg = oMapEx.Message
               iErrCode = oMapEx.ErrorCode
              
				Case "Autodesk.Gis.Map.MapTopologyException"
					oMapTopoEx = DirectCast(oSysEx, Autodesk.Gis.Map.MapTopologyException)
					sMsg = "Ads: " & oMapTopoEx.Message
					iErrCode = oMapTopoEx.AdsErrorCode
            Case Else
               sMsg = sType
         End Select
         If bMsgBox Then
            System.Windows.Forms.MessageBox.Show(sMsg & vbCrLf & CStr(iErrCode), sTitle)
         Else
				AcadDocument.WriteMessage(sTitle & " - Error Code: " & CStr(iErrCode) & vbCrLf & sMsg)
         End If


      Catch oEx As System.Exception
         System.Windows.Forms.MessageBox.Show(oEx.Message, "e301")
      End Try
   End Sub
End Class
