Option Explicit On
Option Strict On
Imports OSGeo.FDO
Imports OSGeo.FDO.ClientServices
Imports OSGeo.FDO.Connections
Imports OSGeo.FDO.Connections.Capabilities
Imports OSGeo.FDO.Commands.SpatialContext
Imports OverlayMgd
Imports OSGeo.FDO.Schema
Imports OSGeo.FDO.Geometry
Imports OSGeo.FDO.Commands.Schema
Imports OSGeo.FDO.Common
Imports OSGeo.FDO.Commands.Feature
Imports OSGeo.FDO.Expression
Imports Autodesk.Gis.Map.DataConnect.UI

Public Class Class1
	Dim o As Autodesk.Fdo.Fdo.Utilities.Schema.XmiSchemaTransform
	Dim d As OSGeo.FDO.Common.Io.IoStream
	Dim msParcelShapePath As String = "D:\aWork\ArcGIS\D\Parcel\topoParcels.shp"
	Dim msLotShapePath As String = "D:\aWork\ArcGIS\D\Lot\topoLots.shp"

	Dim msOverlayShapePath As String = "D:\aWork\ArcGIS\E_Acad\ShpD\Parcels_LotsK.shp"

	Dim sUnionPath As String = "D:\aWork\ArcGIS\E_Acad\topoParcels_UnionK.shp"	''''"D:\aWork\ArcGIS\E_Acad\topoLots_UnionC.sdf"	 'topoLots_UnionDa.sdf
	'topoParcels_UnionK.shp
	Dim msSHPProviderName As String = "OSGeo.SHP.3.6"
	Dim sSDFProviderName As String = "OSGeo.SDF.3.6"
	Dim sSHPPropFileName As String = "DefaultFileLocation"
	Dim sSDFPropFileName As String = "File"
	Public Sub Aa()
		Dim registry As IProviderRegistry = FeatureAccessManager.GetProviderRegistry()
		Dim providers As ProviderCollection = registry.GetProviders()
		Dim oEditor As Autodesk.AutoCAD.EditorInput.Editor = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor
		For Each oProv As Provider In providers
			oEditor.WriteMessage("4!! " & oProv.Name & ":" & oProv.LibraryPath & ":" & CStr(oProv.IsManaged) & vbCrLf)
		Next
		Dim connMgr As IConnectionManager = FeatureAccessManager.GetConnectionManager()


		'Dim f 
		Dim oConnection As IConnectionImp = CType(connMgr.CreateConnection(sSDFProviderName), IConnectionImp)
		Dim oConnInfo As IConnectionInfo = oConnection.ConnectionInfo

		Dim properties As IConnectionPropertyDictionary = oConnInfo.ConnectionProperties
		Dim saNames() As String = properties.PropertyNames
		Dim sConnectionString As String = oConnection.ConnectionString
		oEditor.WriteMessage("5!! " & sConnectionString & vbCrLf)
		Dim isRequired As Boolean

		For iIndex As Integer = 0 To saNames.GetUpperBound(0)
			isRequired = properties.IsPropertyRequired(saNames(iIndex))
			oEditor.WriteMessage("6_" & CStr(iIndex) & " !! " & CStr(isRequired) & " - " & saNames(iIndex) & vbCrLf)
		Next

		properties.SetProperty(sSDFPropFileName, sUnionPath)

		Dim connStateA As ConnectionState = oConnection.Open()
		oEditor.WriteMessage("7!! " & connStateA.ToString() & vbCrLf)

		'	Command 
		Dim cmdCapabilities As ICommandCapabilities = oConnection.CommandCapabilities
		Dim iaCommands() As Integer = cmdCapabilities.Commands
		Dim supportsSelectDistinct As Boolean = cmdCapabilities.SupportsSelectDistinct()

		Dim cmdType As OSGeo.FDO.Commands.CommandType = CType(iaCommands(0), OSGeo.FDO.Commands.CommandType)

		Dim supportsCreateDataStore As Boolean = False
		For i As Integer = 0 To iaCommands.GetUpperBound(0)
			cmdType = CType(iaCommands(i), OSGeo.FDO.Commands.CommandType)
			oEditor.WriteMessage("8!! " & iaCommands(i).ToString() & ":" & cmdType.ToString() & vbCrLf)
			If iaCommands(i) = OSGeo.FDO.Commands.CommandType.CommandType_CreateDataStore Then
				supportsCreateDataStore = True

			End If
		Next

		'		Connection 
		Dim connCapabilities As IConnectionCapabilities = oConnection.ConnectionCapabilities
		Dim LockTypes() As OSGeo.FDO.Commands.Locking.LockType = connCapabilities.LockTypes

		Dim spatialContextExtentTypes() As SpatialContextExtentType = connCapabilities.SpatialContextTypes
		Dim oThreadCapability As ThreadCapability = connCapabilities.ThreadCapability
		Dim supportsConfiguration As Boolean = connCapabilities.SupportsConfiguration


		'	Geometry 
		Dim geometryCapabilities As IGeometryCapabilities = oConnection.GeometryCapabilities
		Dim geometryTypes() As Common.GeometryType = geometryCapabilities.GeometryTypes
		Dim geometryComponentTypes() As Common.GeometryComponentType = geometryCapabilities.GeometryComponentTypes()
		Dim dimensionalities As Integer = geometryCapabilities.Dimensionalities
		Dim HasZ As Boolean = (dimensionalities And 1) = 1
		Dim HasM As Boolean = (dimensionalities And 2) = 2

		'	Schema 
		Dim schemaCapabilities As ISchemaCapabilities = oConnection.SchemaCapabilities
		Dim dataTypes() As DataType = schemaCapabilities.DataTypes
		Dim classTypes() As ClassType = schemaCapabilities.ClassTypes
		Dim reservedCharactersForName As String = schemaCapabilities.ReservedCharactersForName
		Dim maximumDecimalPrecision As Integer = schemaCapabilities.MaximumDecimalPrecision

		Dim supportedAutoGeneratedTypes() As DataType = schemaCapabilities.SupportedAutoGeneratedTypes()
		Dim supportedIdentityPropertyTypes() As DataType = schemaCapabilities.SupportedIdentityPropertyTypes()
		Dim supportsAutoIdGeneration As Boolean = schemaCapabilities.SupportsAutoIdGeneration

		''// get the spatial contexts from a data store
		Dim getSpatialContexts As IGetSpatialContexts = CType(oConnection.CreateCommand(Commands.CommandType.CommandType_GetSpatialContexts), IGetSpatialContexts)
		Dim oSpatialContextReader As ISpatialContextReader = getSpatialContexts.Execute()

		Dim name As String = Nothing
		Dim coordSys As String = Nothing
		Dim wellKnownText As String = Nothing
		Dim desc As String = Nothing
		Dim geomFactory As Geometry.FgfGeometryFactory = New Geometry.FgfGeometryFactory()
		Dim geom As Geometry.IGeometry = Nothing
		Dim sExtent As String = Nothing

		Dim extentType As SpatialContextExtentType
		Dim xyTolerance As Double
		Dim zTolerance As Double
		Dim sCoordinateSystem, sCoordinateSystemWkt As String
		Try
			While oSpatialContextReader.ReadNext()
				name = oSpatialContextReader.GetName()

				coordSys = oSpatialContextReader.GetCoordinateSystem()
				wellKnownText = oSpatialContextReader.GetCoordinateSystemWkt()
				oEditor.WriteMessage("11!! '" & name & "':'" & coordSys & "':'" & wellKnownText & "'" & vbCrLf)
				desc = oSpatialContextReader.GetDescription()
				geom = geomFactory.CreateGeometryFromFgf(oSpatialContextReader.GetExtent())
				sExtent = geom.Text
				extentType = oSpatialContextReader.GetExtentType()
				xyTolerance = oSpatialContextReader.GetXYTolerance()
				zTolerance = oSpatialContextReader.GetZTolerance()
				oEditor.WriteMessage("11a!! " & extentType.ToString() & ":" & sExtent & ":" & CStr(xyTolerance) & vbCrLf)
				sCoordinateSystem = oSpatialContextReader.GetCoordinateSystem()
				sCoordinateSystemWkt = oSpatialContextReader.GetCoordinateSystemWkt()
				oEditor.WriteMessage("11b-!! " & sCoordinateSystem & ":" & sCoordinateSystemWkt & vbCrLf)


			End While
		Catch oEx As Exception
			oEditor.WriteMessage("99a!! " & oEx.Message & ":" & oEx.StackTrace & vbCrLf)
		End Try

		oSpatialContextReader.Dispose()


		'' create a spatial context whose coordinate system is WGS84 and whose extent is the maximum
		''create the extent
		Dim lowerLeft As Geometry.DirectPositionImpl = New Geometry.DirectPositionImpl()

		lowerLeft.X = -180.0
		lowerLeft.Y = -90.0
		Dim upperRight As Geometry.DirectPositionImpl = New Geometry.DirectPositionImpl()
		upperRight.X = 180.0
		upperRight.Y = 90.0
		Dim envelope As Geometry.IEnvelope = geomFactory.CreateEnvelope(lowerLeft, upperRight)
		Dim oGeomA As Geometry.IGeometry = geomFactory.CreateGeometry(envelope)
		Dim baExtent As Byte() = geomFactory.GetFgf(oGeomA)

		If True Then
			Dim createSpatialContext As ICreateSpatialContext = CType(oConnection.CreateCommand(Commands.CommandType.CommandType_CreateSpatialContext), ICreateSpatialContext)


			createSpatialContext.CoordinateSystem = ""
			'	createSpatialContext.CoordinateSystemWkt = "wgs84Wkt"
			createSpatialContext.Description = "This Coordinate System is used for GPS."
			'' a static extent is defined once and never changed
			''/ a dynamic extent grows to accommodate the geometries added to the data store
			createSpatialContext.ExtentType = SpatialContextExtentType.SpatialContextExtentType_Static
			createSpatialContext.Extent = baExtent

			'' the value of Name is assigned to the SpatialContextAssociation attribute of a GeometricPropertyDefinition object during the creation of the logical feature schema
			'' in this way a coordinate system and extent is associated with	the geoemtries

			createSpatialContext.Name = "Israel.israeliGrid"

			Try
				createSpatialContext.Execute()
			Catch oEx As Exception
				oEditor.WriteMessage("99b!! " & oEx.Message & ":" & oEx.StackTrace & vbCrLf)
			End Try
		End If

		'describe a schema
		Dim descSchema As IDescribeSchema = DirectCast(oConnection.CreateCommand(OSGeo.FDO.Commands.CommandType.CommandType_DescribeSchema), IDescribeSchema)
		Dim schemas As FeatureSchemaCollection = descSchema.Execute()
		Dim schema As FeatureSchema = schemas.Item(0)
		Dim classes As ClassCollection = schema.Classes

		Dim featureClass As ClassDefinition = DirectCast(classes.Item(0), ClassDefinition)

		Dim propertiesA As PropertyDefinitionCollection = featureClass.Properties

		Dim [property] As PropertyDefinition = propertiesA.Item(0)
		Dim propertyType As PropertyType = [property].PropertyType

		If (propertyType = propertyType.PropertyType_DataProperty) Then
			Dim dataPropDef As DataPropertyDefinition = DirectCast([property], DataPropertyDefinition)
			Dim dataType As DataType = dataPropDef.DataType
		End If


		oEditor.WriteMessage("12 _ " & schema.Name() & ":" & featureClass.Name & ":" & CStr(xyTolerance) & vbCrLf)
		oEditor.WriteMessage("13 !! " & schema.Name() & ":" & CStr(classes.Count) & vbCrLf)

		oEditor.WriteMessage("14-" & CStr(featureClass.Properties.Count) & ":" & CStr(featureClass.Attributes.Count) & ":" & CStr(featureClass.IdentityProperties.Count) & ":" & CStr(featureClass.BaseIdentityProperties.Count) & vbCrLf)
		Dim oPropDef As PropertyDefinition
		Dim oDataPropDef As OSGeo.FDO.Schema.DataPropertyDefinition
		Dim oGeoPropDef As OSGeo.FDO.Schema.GeometricPropertyDefinition
		Dim oaGeometryType() As OSGeo.FDO.Common.GeometryType
		Dim oGeometryType As OSGeo.FDO.Common.GeometryType

		Dim s As String
		For iIndex As Integer = 0 To featureClass.Properties.Count - 1

			oPropDef = featureClass.Properties.Item(iIndex)
			oEditor.WriteMessage("15$ i=" & CStr(iIndex) & ":" & oPropDef.Name & ":" & CStr(oPropDef.RefCount) & ":" & oPropDef.PropertyType.ToString & ":" & oPropDef.GetType().ToString() & vbCrLf)
			Select Case oPropDef.PropertyType.ToString
				Case "PropertyType_DataProperty"
					oDataPropDef = DirectCast(oPropDef, OSGeo.FDO.Schema.DataPropertyDefinition)

					oEditor.WriteMessage("16^ " & oDataPropDef.Description & ":" & oDataPropDef.FeatureSchema.Name & ":" & CStr(oDataPropDef.Scale) & vbCrLf)
				Case "PropertyType_GeometricProperty"
					oGeoPropDef = DirectCast(oPropDef, OSGeo.FDO.Schema.GeometricPropertyDefinition)
					s = oGeoPropDef.SpatialContextAssociation
					oEditor.WriteMessage("17^ " & s & ":" & oGeoPropDef.FeatureSchema.Name & ":" & CStr(oGeoPropDef.GeometryTypes) & vbCrLf)
					oaGeometryType = oGeoPropDef.SpecificGeometryTypes
					For iType As Integer = 0 To oaGeometryType.GetUpperBound(0)
						oGeometryType = oaGeometryType(iType)
						oEditor.WriteMessage("17x- " & oGeometryType.ToString & vbCrLf)
					Next


					'	oGeoPropDef.Attributes
			End Select




		Next
		For iIndex As Integer = 0 To featureClass.IdentityProperties.Count - 1

			oEditor.WriteMessage("21 " & featureClass.IdentityProperties.Item(0).ToString() & vbCrLf)
		Next

		Dim oSelect As ISelect = CType(oConnection.CreateCommand(OSGeo.FDO.Commands.CommandType.CommandType_Select), ISelect)
		Dim className As Identifier = New Identifier("topoLots_Union_C")

		oSelect.FeatureClassName = className
		Dim oGeometry() As Byte
		Dim oFeatureReader As OSGeo.FDO.Commands.Feature.IFeatureReader = oSelect.Execute()

		Dim iGeo As Integer = 0
		While oFeatureReader.ReadNext()
			featureClass = oFeatureReader.GetClassDefinition
			Try
				oFeatureReader.GetGeometry(0)
				oEditor.WriteMessage("30-- " & ":" & featureClass.Name & vbCrLf)
			Catch ex As Exception
				oEditor.WriteMessage("41err 1!! " & ex.Message & ":" & vbCrLf)

			End Try

			'oEditor.WriteMessage("29-- " & CStr(oFeatureReader.GetDepth()) & ":" & featureClass.Name & vbCrLf)

			'	Exit While
		End While
		'	Dim oGeometry() As Byte = oFeatureReader.GetGeometry(0)
		'	oEditor.WriteMessage("25-- " & oSelect.ToString & ":" & CStr(oGeometry.GetUpperBound(0)) & vbCrLf)


		'	oEditor.WriteMessage("28++ " & oSelectImp.FeatureClassName.Name & vbCrLf)
		Dim schemaA As FeatureSchema = New FeatureSchema("AnApplicationSchema", "This schema contains one feature class.")


		Return

		Dim featClass As FeatureClass = New FeatureClass("AFeatureClass", "This feature class contains one identity property one data property and a feature geometry.")
		Dim propertiesB As OSGeo.FDO.Schema.PropertyDefinitionCollection = featClass.Properties
		Dim idProperties As DataPropertyDefinitionCollection = featClass.IdentityProperties

		Dim idProp As DataPropertyDefinition = New DataPropertyDefinition("ID", "This is the identity property")
		idProp.DataType = DataType.DataType_Int64
		idProp.IsAutoGenerated = True
		idProp.Nullable = False
		idProp.ReadOnly = True
		propertiesB.Add(idProp)
		idProperties.Add(idProp)
		Dim int32Prop As DataPropertyDefinition = New DataPropertyDefinition("Int32Prop", "This is an Int32 property")

		int32Prop.DataType = DataType.DataType_Int32
		propertiesB.Add(int32Prop)
		' add the feature geometry
		Dim featGeomProp As GeometricPropertyDefinition = New GeometricPropertyDefinition("FeatGeomProp", "This is the feature geometry.")
		' associate this geometric property with a spatial context
		' you must have already added the named context to the data store
		' if this property is not set, it is assigned the default spatial context
		' see the Spatial Context topic to read a description of the default spatial context
		featGeomProp.SpatialContextAssociation = "XY-M Spatial Context"
		'by default this geometric property can contain geometries that may be classified as point, curve, surface or solid
		' also by default this geometric property cannot contain geometries that have a Z ordinate or a measure attribute
		propertiesB.Add(featGeomProp)
		' without the following line you would be adding a non-feature geometry(
		featClass.GeometryProperty = featGeomProp
		Dim classesA As ClassCollection = schema.Classes
		classes.Add(featClass)
		'apply the schema
		Dim applySchema As IApplySchema = DirectCast(oConnection.CreateCommand(Commands.CommandType.CommandType_ApplySchema), IApplySchema)

		applySchema.FeatureSchema = schema
		applySchema.Execute()
		applySchema = Nothing
		'destroy the schema
		Dim destroySchema As IDestroySchema = DirectCast(oConnection.CreateCommand(Commands.CommandType.CommandType_DestroySchema), IDestroySchema)

		destroySchema.SchemaName = "AnApplicationSchema"

		destroySchema.Execute()

		'	Dim pos00 As DirectPositionImpl = New DirectPositionImpl(0.0, 0.0)
		Dim pos01 As DirectPositionImpl = New DirectPositionImpl(0.0, 1.0)
		Dim pos12 As DirectPositionImpl = New DirectPositionImpl(1.0, 2.0)
		Dim pos21 As DirectPositionImpl = New DirectPositionImpl(2.0, 1.0)
		Dim pos22 As DirectPositionImpl = New DirectPositionImpl(2.0, 2.0)
		Dim pos23 As DirectPositionImpl = New DirectPositionImpl(2.0, 3.0)
		Dim pos30 As DirectPositionImpl = New DirectPositionImpl(3.0, 0.0)
		Dim pos33 As DirectPositionImpl = New DirectPositionImpl(3.0, 3.0)

		Dim geomFactoryA As FgfGeometryFactory = New FgfGeometryFactory()
		Dim as012122 As ICircularArcSegment = geomFactoryA.CreateCircularArcSegment(pos01, pos21, pos22)
		Dim positions As DirectPositionCollection = New DirectPositionCollection()
		oEditor.WriteMessage(CStr(as012122.IsClosed))
		positions.Add(pos23)
		positions.Add(pos30)
		positions.Add(pos33)
		Dim ls233033 As ILineStringSegment = geomFactoryA.CreateLineStringSegment(positions)
		positions.Clear()

		'ILinearRing 

		positions.Add(pos01)
		positions.Add(pos21)
		positions.Add(pos12)
		positions.Add(pos01)
		Dim lr01211201 As ILinearRing = geomFactoryA.CreateLinearRing(positions)
		positions.Clear()

		'		Collection Classes

		'The following collection classes are used during the construction of the various geometries:
		' Contains IDirectPositionImpl ojbects

		' Contains IPoint objects
		Dim points As PointCollection = New PointCollection()
		' Contains ILineString objects
		Dim lines As LineStringCollection = New LineStringCollection()
		' Contains ICircularArcSegment and ILineStringSegment objects
		Dim curveSegments As CurveSegmentCollection = New CurveSegmentCollection()
		' Contains ICurveString objects
		Dim curves As CurveStringCollection = New CurveStringCollection()
		' Contains ILinearRing objects

		Dim linearRings As LinearRingCollection = New LinearRingCollection()
		' Contains IRing objects
		Dim curveRings As RingCollection = New RingCollection()
		' Contains IPolygon objects
		Dim linearPolygons As PolygonCollection = New PolygonCollection()
		' Contains ICurvePolygon objects
		Dim curvePolygons As CurvePolygonCollection = New CurvePolygonCollection()
		Dim geometries As GeometryCollection = New GeometryCollection()


		'Overlay 
		Try
			FeatureEditor.Overlay("topoLots", "topoParcels", "Union", "D:\aWork\ArcGIS\E_Acad\topoLots_UnionDa.sdf", "topoLots_Union_Da", 6, 0.01, 0.5, 0.5)
		Catch oEx As Exception
			System.Windows.Forms.MessageBox.Show(oEx.Message, "FeatureEditor 124a")
		End Try


		oConnection.Close()
	End Sub
	Public Sub Ab()
		Dim oEditor As Autodesk.AutoCAD.EditorInput.Editor = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor
		Dim connMgr As IConnectionManager = FeatureAccessManager.GetConnectionManager()

		'Dim f 
		Dim oConnection As IConnectionImp = CType(connMgr.CreateConnection(msSHPProviderName), IConnectionImp)
		Dim connInfo As IConnectionInfo = oConnection.ConnectionInfo

		Dim properties As IConnectionPropertyDictionary = connInfo.ConnectionProperties

		properties.SetProperty(sSHPPropFileName, msParcelShapePath)	'sUnionPath

		Dim connStateA As ConnectionState = oConnection.Open()

		oConnection.Flush()
		Dim descSchema As IDescribeSchema = DirectCast(oConnection.CreateCommand(OSGeo.FDO.Commands.CommandType.CommandType_DescribeSchema), IDescribeSchema)
		Dim schemas As FeatureSchemaCollection = descSchema.Execute()
		Dim schema As FeatureSchema = schemas.Item(0)


		Dim classes As ClassCollection = schema.Classes

		Dim featureClass As ClassDefinition = DirectCast(classes.Item(0), ClassDefinition)
		Dim colProps As OSGeo.FDO.Schema.PropertyDefinitionCollection = featureClass.Properties
		Dim oPropDef As PropertyDefinition
		Dim oDataPropDef As OSGeo.FDO.Schema.DataPropertyDefinition
		Dim oGeoPropDef As OSGeo.FDO.Schema.GeometricPropertyDefinition
		Dim oaGeometryType() As OSGeo.FDO.Common.GeometryType
		Dim oGeometryType As OSGeo.FDO.Common.GeometryType
		Dim s As String
		For iIndex As Integer = 0 To colProps.Count - 1

			oPropDef = colProps.Item(iIndex)
			oEditor.WriteMessage("15$ i=" & CStr(iIndex) & ":" & oPropDef.Name & ":" & CStr(oPropDef.RefCount) & ":" & oPropDef.PropertyType.ToString & ":" & oPropDef.GetType().ToString() & vbCrLf)
			Select Case oPropDef.PropertyType.ToString
				Case "PropertyType_DataProperty"
					oDataPropDef = DirectCast(oPropDef, OSGeo.FDO.Schema.DataPropertyDefinition)

					oEditor.WriteMessage("16^ " & oDataPropDef.Description & ":" & oDataPropDef.FeatureSchema.Name & ":" & CStr(oDataPropDef.Scale) & vbCrLf)
				Case "PropertyType_GeometricProperty"
					oGeoPropDef = DirectCast(oPropDef, OSGeo.FDO.Schema.GeometricPropertyDefinition)
					s = oGeoPropDef.SpatialContextAssociation
					oEditor.WriteMessage("17^ " & s & ":" & oGeoPropDef.FeatureSchema.Name & ":" & CStr(oGeoPropDef.GeometryTypes) & vbCrLf)
					oaGeometryType = oGeoPropDef.SpecificGeometryTypes
					For iType As Integer = 0 To oaGeometryType.GetUpperBound(0)
						oGeometryType = oaGeometryType(iType)
						oEditor.WriteMessage("17x- " & oGeometryType.ToString & vbCrLf)
					Next


					'	oGeoPropDef.Attributes
			End Select




		Next


		Dim oSelect As ISelect = CType(oConnection.CreateCommand(OSGeo.FDO.Commands.CommandType.CommandType_Select), ISelect)



		Dim className As Identifier = New Identifier("topoParcels")	'topoParcels_UnionK

		oSelect.FeatureClassName = className
		Dim oGeometry() As Byte
		Dim oFeatureReader As OSGeo.FDO.Commands.Feature.IFeatureReader = oSelect.Execute()
		Dim iGeo As Integer = 0
		Dim geomFactory As Geometry.FgfGeometryFactory = New Geometry.FgfGeometryFactory()
		Dim geom As Geometry.IGeometry = Nothing

		'	Dim featureClass As ClassDefinition
		While oFeatureReader.ReadNext()
			featureClass = oFeatureReader.GetClassDefinition
			Try
				oGeometry = oFeatureReader.GetGeometry(2)
				geom = geomFactory.CreateGeometryFromFgf(oGeometry)
				oEditor.WriteMessage("25%-- " & CStr(geom.Dimensionality) & ":" & geom.Text & vbCrLf)


				oEditor.WriteMessage("30-- " & ":" & featureClass.Name & vbCrLf)
			Catch ex As Exception
				oEditor.WriteMessage("40err 1!! " & ex.Message & ":" & vbCrLf)
				Exit While
			End Try

			oEditor.WriteMessage("29-- " & CStr(oGeometry.GetUpperBound(0)) & ":" & featureClass.Name & vbCrLf)
			Exit While

		End While


	End Sub
	Public Sub Ac()
		Dim oEditor As Autodesk.AutoCAD.EditorInput.Editor = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor
		Try
			FeatureEditor.Overlay("topoLots", "topoParcels", "Union", "D:\aWork\ArcGIS\E_Acad\topoLots_UnionKa.sdf", "topoLots_Union_Ka", 6, 0.01, 0.5, 0.5)
		Catch oEx As Exception
			System.Windows.Forms.MessageBox.Show(oEx.Message, "FeatureEditor 129")
		End Try

		Dim connMgr As IConnectionManager = FeatureAccessManager.GetConnectionManager()

		'Dim f 
		Dim oConnection As IConnectionImp = CType(connMgr.CreateConnection(msSHPProviderName), IConnectionImp)
		Dim connInfo As IConnectionInfo = oConnection.ConnectionInfo

		Dim properties As IConnectionPropertyDictionary = connInfo.ConnectionProperties

		properties.SetProperty(sSHPPropFileName, msParcelShapePath)	'sUnionPath

		Dim connStateA As ConnectionState = oConnection.Open()
	End Sub
	Public Sub Ad()
		Dim oEditor As Autodesk.AutoCAD.EditorInput.Editor = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor
		Dim oAcMapDataConnectUI As AcMapDataConnectUI = New AcMapDataConnectUI()

		oAcMapDataConnectUI.SelectProvider(msSHPProviderName)
		oAcMapDataConnectUI.ConnectedToFeatureSource(msParcelShapePath)
		oAcMapDataConnectUI.FeatureSourceAdded("topoParcels")
		oEditor.WriteMessage("102 EEE !! " & vbCrLf)
		oAcMapDataConnectUI.LayerSourceAdded("topoParcels")
		oEditor.WriteMessage("120 !! " & vbCrLf)
		oAcMapDataConnectUI.SelectFeatureSource("topoParcels")
		oEditor.WriteMessage("121 !! " & vbCrLf)
		oAcMapDataConnectUI.ConnectedToFeatureSource(msLotShapePath)
		oAcMapDataConnectUI.FeatureSourceAdded("topoLots")
		oEditor.WriteMessage("110 !! " & vbCrLf)
		oAcMapDataConnectUI.LayerSourceAdded("topoLots")
		oEditor.WriteMessage("125 !! " & vbCrLf)
		oAcMapDataConnectUI.SelectFeatureSource("topoLots")
		oEditor.WriteMessage("140 !! " & vbCrLf)
		oAcMapDataConnectUI.AcadDocumentActivatedHelper()
		oEditor.WriteMessage("150 !! " & vbCrLf)
		Try
			'FeatureEditor.Overlay("topoLots", "topoParcels", "Union", "D:\aWork\ArcGIS\E_Acad\topoLots_UnionMa.sdf", "topoLots_Union_Ma", 6, 0.01, 0.5, 0.5)
		Catch oEx As Exception
			System.Windows.Forms.MessageBox.Show(oEx.Message, "FeatureEditor 129")
		End Try
	End Sub
	Public Sub Ba()
		'// get the spatial contexts from a data store
		Dim oEditor As Autodesk.AutoCAD.EditorInput.Editor = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor
		Dim connMgr As IConnectionManager = FeatureAccessManager.GetConnectionManager()

		'Dim f 
		Dim oDynamic As Object = connMgr.CreateConnection(msSHPProviderName)
		'	System.Windows.Forms.MessageBox.Show(oDynamic.ToString, "02_100")

		Dim oConnection As IConnectionImp = DirectCast(connMgr.CreateConnection(msSHPProviderName), IConnectionImp)
		Dim connInfo As IConnectionInfo = oConnection.ConnectionInfo


		Dim properties As IConnectionPropertyDictionary = connInfo.ConnectionProperties

		properties.SetProperty(sSHPPropFileName, msParcelShapePath)	'sUnionPath

		Dim connStateA As ConnectionState = oConnection.Open()


		Dim getSpatialContexts As IGetSpatialContexts = CType(oConnection.CreateCommand(OSGeo.FDO.Commands.CommandType.CommandType_GetSpatialContexts), IGetSpatialContexts)
		Dim reader As ISpatialContextReader = getSpatialContexts.Execute()
		Dim name As String = Nothing
		Dim coordSys As String = Nothing
		Dim wellKnownText As String = Nothing
		Dim desc As String = Nothing
		Dim geomFactory As FgfGeometryFactory = New FgfGeometryFactory()
		Dim geom As IGeometry = Nothing
		Dim extent As String = Nothing
		Dim extentType As SpatialContextExtentType
		Dim xyTolerance As Double
		Dim zTolerance As Double
		Dim btaBYTE() As Byte
		While reader.ReadNext()
			name = reader.GetName()

			coordSys = reader.GetCoordinateSystem()
			wellKnownText = reader.GetCoordinateSystemWkt()
			desc = reader.GetDescription()
			btaBYTE = reader.GetExtent()
			oEditor.WriteMessage("8@ " & CStr(btaBYTE.GetUpperBound(0)) & vbCrLf)
			geom = geomFactory.CreateGeometryFromFgf(btaBYTE)
			extent = geom.Text
			extentType = reader.GetExtentType()
			xyTolerance = reader.GetXYTolerance()
			zTolerance = reader.GetZTolerance()
			oEditor.WriteMessage("9@ " & name & ":" & extent & ":" & CStr(desc) & vbCrLf)
		End While
		reader.Dispose()
		oEditor.WriteMessage("10@ " & geom.Text & vbCrLf)

		''// describe a schema
		Dim descSchema As IDescribeSchema = CType(oConnection.CreateCommand(OSGeo.FDO.Commands.CommandType.CommandType_DescribeSchema), IDescribeSchema)

		Dim schemas As FeatureSchemaCollection = descSchema.Execute()
		Dim schema As FeatureSchema = schemas.Item(0)

		Dim classes As ClassCollection = schema.Classes
		Dim oClassDef As ClassDefinition = classes.Item(0)
		oEditor.WriteMessage("11@ " & oClassDef.ToString() & vbCrLf)

		Dim featureClassA As FeatureClass = DirectCast(oClassDef, FeatureClass)

		Dim propertiesA As PropertyDefinitionCollection = featureClassA.Properties

		oEditor.WriteMessage("12@ " & CStr(propertiesA.Count) & vbCrLf)

		Dim propertyA As PropertyDefinition = propertiesA.Item(0)

		Dim propertyType As PropertyType = propertyA.PropertyType

		If (propertyType = propertyType.PropertyType_DataProperty) Then
			Dim dataPropDef As DataPropertyDefinition = CType(propertyA, DataPropertyDefinition)
			Dim dataTypeA As DataType = dataPropDef.DataType
		End If
		Dim oGeometricPropertyDef As OSGeo.FDO.Schema.GeometricPropertyDefinition = featureClassA.GeometryProperty
		oEditor.WriteMessage("13@ " & CStr(oGeometricPropertyDef.Name) & vbCrLf)
		oEditor.WriteMessage("14@ " & CStr(oGeometricPropertyDef.SpecificGeometryTypes.GetUpperBound(0)) & vbCrLf)

		oEditor.WriteMessage("15@ " & CStr(oGeometricPropertyDef.SpecificGeometryTypes(0).ToString()) & vbCrLf)
		oEditor.WriteMessage("16@ " & CStr(oGeometricPropertyDef.SpatialContextAssociation) & vbCrLf)


	End Sub
	Public Sub Bb()
		'// get the spatial contexts from a data store
		Dim oEditor As Autodesk.AutoCAD.EditorInput.Editor = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor
		Dim connMgr As IConnectionManager = FeatureAccessManager.GetConnectionManager()

		'Dim f 
		Dim oDynamic As Object = connMgr.CreateConnection(msSHPProviderName)
		'	System.Windows.Forms.MessageBox.Show(oDynamic.ToString, "02_100")

		Dim oConnection As IConnectionImp = DirectCast(connMgr.CreateConnection(msSHPProviderName), IConnectionImp)
		Dim connInfo As IConnectionInfo = oConnection.ConnectionInfo


		Dim properties As IConnectionPropertyDictionary = connInfo.ConnectionProperties

		properties.SetProperty(sSHPPropFileName, msOverlayShapePath)	'sUnionPath

		Dim connStateA As ConnectionState = oConnection.Open()

		Dim className As Identifier = New Identifier("Parcels_LotsK")		'"topoLots"
		Dim oSelect As ISelect = CType(oConnection.CreateCommand(OSGeo.FDO.Commands.CommandType.CommandType_Select), ISelect)

		oSelect.FeatureClassName = className
		Dim oFilter As OSGeo.FDO.Filter.Filter = OSGeo.FDO.Filter.Filter.Parse("ID >= 0")
		'''''''''''	oSelect.Filter = oFilter

		'DIM computedId as ComputedIdentifier= Expression.Parse("(ToString(Date TimeProp) as computedId)") as ComputedIdentifier
		'	oSelect.PropertyNames.Add(computedId)
		Dim oFeatureReader As IFeatureReader = oSelect.Execute()
		Dim oFeatureReaderA As IFeatureReader

		Dim oClassDef As ClassDefinition = Nothing

		Dim geomFactory As FgfGeometryFactory = New FgfGeometryFactory()
		Dim oFeatureClass As FeatureClass
		Dim btaByte() As Byte
		Dim iIndex As Integer = 0
		Dim oGeom As IGeometry = Nothing
		Dim oGeometricPropertyDef As OSGeo.FDO.Schema.GeometricPropertyDefinition
		Dim oaTypes() As OSGeo.FDO.Common.GeometryType
		Dim ofeatureClassProperties As PropertyDefinitionCollection
		Dim oPropDef As PropertyDefinition
		Dim oDataPropDef As OSGeo.FDO.Schema.DataPropertyDefinition
		Dim oGeoPropDef As OSGeo.FDO.Schema.GeometricPropertyDefinition
		Dim oPropertyType As OSGeo.FDO.Schema.PropertyType
		Dim iGeoIndex As Integer
		Dim bFlag As Boolean = True
		While ofeatureReader.ReadNext()
			If oClassDef Is Nothing Then
				oClassDef = ofeatureReader.GetClassDefinition()
				ofeatureClassProperties = oClassDef.Properties
				oFeatureClass = DirectCast(oClassDef, FeatureClass)
				oGeometricPropertyDef = oFeatureClass.GeometryProperty
				oEditor.WriteMessage("21a@  " & oFeatureClass.Name & ":" & CStr(oGeometricPropertyDef.GeometryTypes) & vbCrLf)
				oEditor.WriteMessage("21x@  " & oClassDef.Name & ":" & CStr(oClassDef.IdentityProperties.Count) & ":" & CStr(oClassDef.Properties.Count) & ":" & CStr(oClassDef.RefCount) & vbCrLf)
				For iPropIndex As Integer = 0 To oClassDef.Properties.Count - 1
					oPropDef = oClassDef.Properties.Item(iPropIndex)
					oPropertyType = oPropDef.PropertyType
					Select Case oPropertyType.ToString()
						Case "PropertyType_DataProperty"
							oDataPropDef = DirectCast(oPropDef, OSGeo.FDO.Schema.DataPropertyDefinition)

							oEditor.WriteMessage("16@ " & CStr(iPropIndex) & ":" & oDataPropDef.Description & ":" & CStr(oDataPropDef.Scale) & vbCrLf)
						Case "PropertyType_GeometricProperty"
							oGeoPropDef = DirectCast(oPropDef, OSGeo.FDO.Schema.GeometricPropertyDefinition)
							oEditor.WriteMessage("17@ " & CStr(iPropIndex) & ":" & oGeoPropDef.GeometryTypes & ":" & CStr(oGeoPropDef.SpatialContextAssociation) & vbCrLf)
							'	oEditor.WriteMessage("17@ " & CStr(iPropIndex) & ":" & oGeoPropDef.GeometryTypes & ":" & oGeoPropDef.FeatureSchema.Name & ":" & CStr(oGeoPropDef.SpatialContextAssociation) & vbCrLf)

							iGeoIndex = iPropIndex
						Case Else
							oEditor.WriteMessage("18@ " & CStr(iPropIndex) & ":" & oPropDef.ToString() & vbCrLf)
					End Select
				Next
				oaTypes = oGeometricPropertyDef.SpecificGeometryTypes

				For iTypeIndex As Integer = 0 To oaTypes.GetUpperBound(0)
					oEditor.WriteMessage("22@- " & CStr(iTypeIndex) & ":" & oaTypes(iTypeIndex).ToString() & vbCrLf)
				Next
			End If
			'	oEditor.WriteMessage("23@: " & CStr(reader.GetDepth()) & vbCrLf)
			

			If bFlag Then
				Try
					btaByte = oFeatureReader.GetGeometry(iGeoIndex)
					oEditor.WriteMessage("30@- " & CStr(btaByte.GetUpperBound(0)) & ":" & "!!!" & vbCrLf)
					'''''''''''''''''	oGeom = geomFactory.CreateGeometryFromWkb(btaByte)
				Catch oEx As Exception
					oEditor.WriteMessage("99@ " & CStr(iGeoIndex) & ":" & CStr(oEx.Message) & vbCrLf)
					bFlag = False
				End Try
			End If
		End While
		ofeatureReader.Dispose()

	End Sub
	Protected Overrides Sub Finalize()
		MyBase.Finalize()
	End Sub

	Public Sub New()

	End Sub
End Class
