TRANSFER-TYPE 2;
WINDOW 197000,664500,198200,666000;
SURVEYOR 593;
GUSH 5499;
SCALE 2500;
SURVEY-DATE 19/11/2014;
SETTLEMENT 8500;
MUNICIPALITY 8500;
COUNTY 43;
SHEET-NUM 5;
TALAR-NUM  498/2015;
TALAR-SERIAL 13/680/5;
FINISH-DATE 16/03/2015;
PARCELS 3, 11;
PLACE ראש;
ORDERER משרד הבינוי והשיכון;
TALAR-COMMENT  התוכנית מבוססת על מפת גוש רישום מס. 5499
כל הגבולות שלא תוארו אחרת הם לא מסויגים.
כל סימני המדידה שלא תוארו אחרת הם מסוג לא סומנו בשדה.
הגבולות נקבעו בשיטה אנליטית והפרטים בשיטה קוטבית, פוטוגרמטרית
התוכנית הוכנה בהתאם לתבעות מספר רנ/275/א,רנ/300/א,מח/167.;
TABA-NAMES רנ275א;
AREA-UNITS DUNAM;
