TRANSFER-TYPE 2 ;
WINDOW 228718,723974,228842,724408, ;
SURVEYOR 593 ;
GUSH 16709 ;
PARCELS 6 ;
TEMP-PARCELS  ;
SCALE 1250 ;
SURVEY-DATE 05/09/2001 ;
UPDATE-DATE 12/01/2002 ;
FINISH-DATE 01/01/2003 ;
TALAR-SERIAL 01/399/ 1/..‚ ;
PLACE €”…Œ„ ;
SETTLEMENT 7700 ;
MUNICIPALITY 7700 ;
COUNTY 23 ;
ORDERER Ž„Œ Ž—˜—’‰ ‰™˜€Œ ;
SHEET-NUM 1 ;


TABA-NAMES  ;
WORK-ORDER  ;
GUSH-CHANGE  ;
TALAR-NUM  ;
FIELD-BOOKS  ;
DISTO-BOOKS  ;
GENERAL-COMMENT  ;
AREA-UNITS DUNAM ;






TALAR-COMMENT `.000 '‘Ž …™‰˜ ™…‚ š”Ž Œ’ š‘‘…Ž š‰‹š„.1`
              `‰Œ™ 01/399/4/..‚ '‘Ž …™‰˜ ‰‹˜–Œ š‰‹š Œ’ š‘‘…Ž š‰‹š„.2`
              `.----™…‚™--˜”‘Ž ‰”Œ ---- Š‰˜€š Œ€˜™‰ ‰…”‰ŽŒ †‹˜Ž„ Œ„Ž ˜™‰€™`
              `0000 …™‰˜ ™…‚ š”Ž Œ’ š‘‘…Ž š‰‹š„.3`
              `‰Œ™ 01/400/5/..‚ '‘Ž …™‰˜ ‰‹˜–Œ š‰‹š Œ’…`
              `.000 ™…‚™--˜”‘Ž ‰”Œ ---Š‰˜€š Œ€˜™‰ ‰…”‰ŽŒ †‹˜Ž„ Œ„Ž ˜™‰€™`
              `0000 š…—Œ‡„ ‡ˆ™… š…Œ…‚„.4`
              `.0000 '‘Ž …™‰˜ ™…‚ š”ŽŽ …‡—Œ`
              `.‚‰…‘Ž €Œ ‚…‘Ž „ š˜‡€ …˜€…š €Œ™ š…Œ…‚„ Œ‹.5`
              `.š‰…† Œ†˜ ‚…‘Ž „ š˜‡€ …˜€…š €Œ™ „ƒ‰ƒŽ„ ‰Ž‰‘ Œ‹.6`
              `.‰’˜€ š…—Œ‡ ‰˜”‘Ž „ ‰’…˜Ž ‰‰˜‚…‘ ‰˜”‘Ž„.7`
              `‘…‘‰ š…‰‹šŽ …–Ž…€-----„˜— š…ƒ…—.8`
              `.„™ƒ‡„ Œ€˜™‰ š™˜Œ …˜Žš…„…`
              `.š‰ˆ…— „ˆ‰™ …ƒƒŽ š…Œ…‚„.9`
              `.š‰˜ˆŽ˜‚…ˆ…”… š‰ˆ…— „ˆ‰™ …ƒƒŽ ‰ˆ˜”„.10`
              `.š‰˜ˆŽ˜‚…ˆ…”… š‰ˆ…— „ˆ‰™ …ƒƒŽ ‰ˆ˜”„… š…Œ…‚„.11`
              `.000'‘Ž ’"š - Œ €š„ „‹…„ š‰‹š„.12`
              `.000'‘Ž –"™š - Œ €š„ „‹…„ š‰‹š„.13`
              `.0000 ’ƒ…’ '‘Ž.14`
               .00000 - ˆ—‰‰…˜” '‘Ž.15 ;


